import React, { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowRight, ArrowLeft, Users, Check, X, ChevronDown, ChevronUp, Sparkles, Building, Cpu, Brain, Target } from 'lucide-react'
import useOnboardingStore from '../../store/onboardingStore'

// Mock ICP templates that would be generated by AI agents
const generateMockICPs = (company, product, strategy) => {
  const icpTemplates = [
    {
      id: 'desperate-scaler',
      label: 'Desperate Scaler',
      summary: `High-growth ${company.industry || 'tech'} company (50-200 people) with chaotic operations, using legacy tools, desperately needing to scale their ${product.mainJob?.split(' ')[0] || 'processes'}.`,
      firmographics: {
        employeeRange: '50-200',
        industries: [company.industry || 'Software / SaaS'],
        stage: ['series-a', 'series-b+'],
        regions: ['North America', 'EMEA']
      },
      technographics: {
        currentStack: ['Salesforce', 'HubSpot', 'Spreadsheets'],
        painPoints: ['Manual processes', 'Data silos', 'Scaling bottlenecks']
      },
      psychographics: {
        painPoints: ['Growth is outpacing ops', 'Team burnout from manual work', 'Leadership pressure to scale'],
        motivations: ['Automate before we break', 'Look competent to board', 'Free up team for strategic work'],
        triggers: ['New funding round', 'CEO mandate to scale', 'Key hire joined with higher standards']
      },
      buyingCommittee: [
        { role: 'Decision Maker', title: 'VP Operations or COO' },
        { role: 'Champion', title: 'Director of Analytics' },
        { role: 'Economic Buyer', title: 'CFO' }
      ],
      fitScore: 92,
      selected: true
    },
    {
      id: 'frustrated-optimizer',
      label: 'Frustrated Optimizer',
      summary: `Established company (200-1000 people) that's tried other solutions but found them lacking. Looking for something that actually works for their ${product.usedBy?.join(', ') || 'team'}.`,
      firmographics: {
        employeeRange: '200-1000',
        industries: [company.industry || 'Enterprise'],
        stage: ['established-sme', 'enterprise'],
        regions: ['Global']
      },
      technographics: {
        currentStack: ['Enterprise tools', 'Custom solutions'],
        painPoints: ['Previous tool failed', 'Over-engineered solutions', 'Poor adoption']
      },
      psychographics: {
        painPoints: ['Wasted budget on wrong tools', 'Team resistant to new tools', 'Need quick wins to justify change'],
        motivations: ['Find something that sticks', 'Prove value fast', 'Simplify their stack'],
        triggers: ['Contract renewal coming up', 'New leadership with fresh perspective', 'Competitive pressure']
      },
      buyingCommittee: [
        { role: 'Decision Maker', title: 'CTO or VP Engineering' },
        { role: 'Champion', title: 'Product Manager' },
        { role: 'Blocker', title: 'IT Security' }
      ],
      fitScore: 78,
      selected: true
    },
    {
      id: 'risk-mitigator',
      label: 'Risk Mitigator',
      summary: `Risk-averse organization in ${company.industry || 'regulated industry'} that needs proven, compliant solutions. Values stability and support over cutting-edge features.`,
      firmographics: {
        employeeRange: '500+',
        industries: ['Finance', 'Healthcare', company.industry || 'Enterprise'],
        stage: ['enterprise'],
        regions: ['North America', 'EU']
      },
      technographics: {
        currentStack: ['Legacy enterprise systems', 'Compliance tools'],
        painPoints: ['Compliance requirements', 'Audit trails', 'Security concerns']
      },
      psychographics: {
        painPoints: ['Regulatory pressure', 'Fear of vendor risk', 'Need for audit trails'],
        motivations: ['Check compliance boxes', 'Reduce operational risk', 'Sleep well at night'],
        triggers: ['Upcoming audit', 'New regulation announced', 'Board pressure on risk management']
      },
      buyingCommittee: [
        { role: 'Decision Maker', title: 'Chief Risk Officer' },
        { role: 'Champion', title: 'Compliance Manager' },
        { role: 'Technical Eval', title: 'Security Team' },
        { role: 'Economic Buyer', title: 'CFO' }
      ],
      fitScore: 65,
      selected: false
    }
  ]
  return icpTemplates
}

const ICPCard = ({ icp, onToggle, isExpanded, onExpand }) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className={`
        rounded-2xl border transition-all
        ${icp.selected 
          ? 'bg-gradient-to-br from-amber-500/10 to-amber-600/5 border-amber-500/30' 
          : 'bg-zinc-900/50 border-white/10'
        }
      `}
    >
      {/* Header */}
      <div className="p-6">
        <div className="flex items-start justify-between mb-4">
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-lg ${icp.selected ? 'bg-amber-500/20' : 'bg-white/5'}`}>
              <Users className={`w-5 h-5 ${icp.selected ? 'text-amber-400' : 'text-white/40'}`} />
            </div>
            <div>
              <h3 className="text-lg font-medium text-white">{icp.label}</h3>
              <div className="flex items-center gap-2 mt-1">
                <span className={`text-xs px-2 py-0.5 rounded-full ${
                  icp.fitScore >= 80 ? 'bg-emerald-500/20 text-emerald-400' :
                  icp.fitScore >= 60 ? 'bg-amber-500/20 text-amber-400' :
                  'bg-white/10 text-white/40'
                }`}>
                  {icp.fitScore}% fit
                </span>
              </div>
            </div>
          </div>
          <button
            onClick={() => onToggle(icp.id, !icp.selected)}
            className={`
              p-2 rounded-lg transition-colors
              ${icp.selected 
                ? 'bg-amber-500 text-black hover:bg-amber-400' 
                : 'bg-white/10 text-white/40 hover:bg-white/20'
              }
            `}
          >
            {icp.selected ? <Check className="w-4 h-4" /> : <X className="w-4 h-4" />}
          </button>
        </div>

        <p className="text-sm text-white/60 leading-relaxed">{icp.summary}</p>

        <button
          onClick={() => onExpand(isExpanded ? null : icp.id)}
          className="flex items-center gap-1 mt-4 text-xs text-white/40 hover:text-white/60 transition-colors"
        >
          {isExpanded ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
          {isExpanded ? 'Less details' : 'More details'}
        </button>
      </div>

      {/* Expanded details */}
      {isExpanded && (
        <motion.div
          initial={{ height: 0, opacity: 0 }}
          animate={{ height: 'auto', opacity: 1 }}
          exit={{ height: 0, opacity: 0 }}
          className="border-t border-white/5 p-6 space-y-6"
        >
          {/* Firmographics */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <Building className="w-4 h-4 text-amber-400" />
              <h4 className="text-xs uppercase tracking-wider text-white/40">Firmographics</h4>
            </div>
            <div className="grid grid-cols-2 gap-3 text-sm">
              <div>
                <span className="text-white/40">Size:</span>
                <span className="text-white ml-2">{icp.firmographics.employeeRange}</span>
              </div>
              <div>
                <span className="text-white/40">Stage:</span>
                <span className="text-white ml-2">{icp.firmographics.stage.join(', ')}</span>
              </div>
            </div>
            <div className="flex flex-wrap gap-1 mt-2">
              {icp.firmographics.industries.map((ind, i) => (
                <span key={i} className="px-2 py-0.5 bg-white/5 rounded text-xs text-white/50">
                  {ind}
                </span>
              ))}
            </div>
          </div>

          {/* Technographics */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <Cpu className="w-4 h-4 text-amber-400" />
              <h4 className="text-xs uppercase tracking-wider text-white/40">Technographics</h4>
            </div>
            <div className="flex flex-wrap gap-1">
              {icp.technographics.currentStack.map((tech, i) => (
                <span key={i} className="px-2 py-0.5 bg-orange-500/10 text-orange-400/80 rounded text-xs">
                  {tech}
                </span>
              ))}
            </div>
          </div>

          {/* Psychographics */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <Brain className="w-4 h-4 text-amber-400" />
              <h4 className="text-xs uppercase tracking-wider text-white/40">Psychographics</h4>
            </div>
            <div className="space-y-2">
              <div>
                <span className="text-xs text-white/30">Pain Points:</span>
                <ul className="mt-1 space-y-1">
                  {icp.psychographics.painPoints.map((pain, i) => (
                    <li key={i} className="text-sm text-red-400/70 flex items-center gap-2">
                      <span className="w-1 h-1 bg-red-400 rounded-full" />
                      {pain}
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <span className="text-xs text-white/30">Motivations:</span>
                <ul className="mt-1 space-y-1">
                  {icp.psychographics.motivations.map((mot, i) => (
                    <li key={i} className="text-sm text-emerald-400/70 flex items-center gap-2">
                      <span className="w-1 h-1 bg-emerald-400 rounded-full" />
                      {mot}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>

          {/* Buying Committee */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <Target className="w-4 h-4 text-amber-400" />
              <h4 className="text-xs uppercase tracking-wider text-white/40">Buying Committee</h4>
            </div>
            <div className="space-y-2">
              {icp.buyingCommittee.map((member, i) => (
                <div key={i} className="flex items-center gap-3 text-sm">
                  <span className="px-2 py-0.5 bg-white/5 rounded text-xs text-white/40">
                    {member.role}
                  </span>
                  <span className="text-white/60">{member.title}</span>
                </div>
              ))}
            </div>
          </div>
        </motion.div>
      )}
    </motion.div>
  )
}

const StepICPs = () => {
  const navigate = useNavigate()
  const { company, product, strategy, icps, setICPs, toggleICP, nextStep, prevStep } = useOnboardingStore()
  
  const [expandedICP, setExpandedICP] = useState(null)
  const [isGenerating, setIsGenerating] = useState(true)

  // Generate ICPs on mount
  useEffect(() => {
    if (icps.length === 0) {
      // Simulate AI generation
      setTimeout(() => {
        const generated = generateMockICPs(company, product, strategy)
        setICPs(generated)
        setIsGenerating(false)
      }, 2000)
    } else {
      setIsGenerating(false)
    }
  }, [])

  const selectedCount = icps.filter(icp => icp.selected).length

  const handleNext = () => {
    nextStep()
    navigate('/onboarding/warplan')
  }

  const handleBack = () => {
    prevStep()
    navigate('/onboarding/strategy')
  }

  if (isGenerating) {
    return (
      <div className="min-h-[calc(100vh-140px)] flex items-center justify-center">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="text-center"
        >
          <div className="relative mb-8">
            <div className="w-20 h-20 border-4 border-amber-500/20 rounded-full animate-pulse" />
            <Sparkles className="absolute inset-0 m-auto w-8 h-8 text-amber-400 animate-pulse" />
          </div>
          <h2 className="text-2xl font-light text-white mb-2">Generating your ICPs...</h2>
          <p className="text-white/40">Analyzing your inputs to create ideal customer profiles</p>
        </motion.div>
      </div>
    )
  }

  return (
    <div className="min-h-[calc(100vh-140px)] flex flex-col">
      <div className="flex-1 max-w-5xl mx-auto w-full px-6 py-12">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-10"
        >
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 bg-amber-500/10 rounded-xl">
              <Users className="w-6 h-6 text-amber-400" />
            </div>
            <span className="text-xs uppercase tracking-[0.2em] text-amber-400/60">
              Step 6 of 8 · ICP Reveal
            </span>
          </div>
          <h1 className="text-3xl md:text-4xl font-light text-white mb-3">
            Here's who you're <span className="italic text-amber-200">really built for</span>
          </h1>
          <p className="text-white/40 max-w-xl">
            Based on your inputs, we've identified {icps.length} ideal customer profiles. 
            Select the ones you want to target.
          </p>
        </motion.div>

        {/* ICP Cards */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {icps.map((icp, index) => (
            <motion.div
              key={icp.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1 }}
            >
              <ICPCard
                icp={icp}
                onToggle={toggleICP}
                isExpanded={expandedICP === icp.id}
                onExpand={setExpandedICP}
              />
            </motion.div>
          ))}
        </div>

        {/* Selection summary */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4 }}
          className="mt-8 p-4 bg-white/5 rounded-xl text-center"
        >
          <span className="text-white/60">
            {selectedCount} of {icps.length} ICPs selected
          </span>
          {selectedCount === 0 && (
            <span className="text-amber-400 ml-2">
              (Select at least one to continue)
            </span>
          )}
        </motion.div>
      </div>

      {/* Footer */}
      <div className="border-t border-white/5 bg-zinc-950/80 backdrop-blur-xl sticky bottom-0">
        <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
          <button
            onClick={handleBack}
            className="flex items-center gap-2 text-white/40 hover:text-white text-sm transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back
          </button>

          <button
            onClick={handleNext}
            disabled={selectedCount === 0}
            className={`
              flex items-center gap-2 px-6 py-3 rounded-xl font-medium transition-all
              ${selectedCount > 0
                ? 'bg-amber-500 hover:bg-amber-400 text-black'
                : 'bg-white/10 text-white/30 cursor-not-allowed'
              }
            `}
          >
            Generate War Plan
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  )
}

export default StepICPs

