# Google Cloud App Engine configuration
runtime: nodejs20

# Instance class
instance_class: F2

# Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

# Environment variables (set these in Cloud Console or use gcloud)
env_variables:
  NODE_ENV: "production"
  SUPABASE_URL: "your_supabase_url"
  SUPABASE_SERVICE_KEY: "your_supabase_service_key"
  POSTHOG_KEY: "your_posthog_key"
  POSTHOG_HOST: "https://app.posthog.com"

# Health check
handlers:
  - url: /health
    script: auto
    secure: always

  - url: /.*
    script: auto
    secure: always

# Network settings
network:
  session_affinity: true

# Resources
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
