"use client";

import { useEffect, useState, useRef } from "react";
import { useRouter } from "next/navigation";
import gsap from "gsap";
import {
    ArrowLeft,
    CheckCircle,
    Clock,
    FileText,
    MessageSquare,
    Link,
    Play,
    StopCircle
} from "lucide-react";

import { useMovesStore } from "@/stores/movesStore"; // Assuming store availability
import { BlueprintCard } from "@/components/ui/BlueprintCard";
import { BlueprintButton, SecondaryButton } from "@/components/ui/BlueprintButton";
import { BlueprintBadge } from "@/components/ui/BlueprintBadge";

export default function MoveDetailPage({ params }: { params: { id: string } }) {
    const router = useRouter();
    const pageRef = useRef<HTMLDivElement>(null);
    const { moves } = useMovesStore();
    const [move, setMove] = useState<any>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        // Fallback or find
        const found = moves.find(m => m.id === params.id) ||
            moves[0] ||
            { id: "1", title: "Keynote Announcement", status: "active", priority: "high", description: "Launch the Q1 product roadmap video on LinkedIn." };

        if (found) {
            setMove(found);
            setLoading(false);
        } else {
            setLoading(false);
        }
    }, [moves, params.id]);

    useEffect(() => {
        if (!pageRef.current || loading || !move) return;
        gsap.fromTo("[data-anim]", { opacity: 0, y: 10 }, { opacity: 1, y: 0, duration: 0.4, stagger: 0.1 });
    }, [loading, move]);

    if (loading) return <div className="p-12 text-center text-[var(--muted)]">Loading move...</div>;

    return (
        <div ref={pageRef} className="max-w-4xl mx-auto pb-12">
            <button onClick={() => router.back()} className="flex items-center gap-2 text-sm text-[var(--muted)] hover:text-[var(--ink)] mb-6 transition-colors">
                <ArrowLeft size={16} /> Back to Moves
            </button>

            {/* Header */}
            <div className="flex justify-between items-start mb-8 border-b border-[var(--border-subtle)] pb-8" data-anim>
                <div className="space-y-3">
                    <div className="flex items-center gap-3">
                        <span className="font-mono text-xs text-[var(--muted)]">MVP-{move.id}</span>
                        <BlueprintBadge variant={move.priority === 'high' ? 'warning' : 'default'} dot>{move.priority?.toUpperCase() || "NORMAL"}</BlueprintBadge>
                    </div>
                    <h1 className="font-serif text-3xl text-[var(--ink)]">{move.title}</h1>
                </div>
                <div className="flex gap-3">
                    <SecondaryButton>Edit</SecondaryButton>
                    <BlueprintButton variant="primary"><CheckCircle size={16} /> Mark Complete</BlueprintButton>
                </div>
            </div>

            <div className="grid grid-cols-3 gap-8" data-anim>
                {/* Main Content */}
                <div className="col-span-2 space-y-8">
                    <section>
                        <h3 className="font-technical text-[var(--muted)] mb-3">ACTION PLAN</h3>
                        <p className="text-lg text-[var(--ink)] leading-relaxed">
                            {move.description || "No description provided for this move."}
                        </p>
                    </section>

                    <BlueprintCard title="Assets & Outputs" code="ASSETS" padding="none" showCorners>
                        <div className="divide-y divide-[var(--border-subtle)]">
                            <div className="p-4 flex items-center gap-3 hover:bg-[var(--canvas)] transition-colors cursor-pointer">
                                <div className="p-2 bg-[var(--blueprint-light)] text-[var(--blueprint)] rounded-[var(--radius-sm)]"><FileText size={18} /></div>
                                <div className="flex-1"><h4 className="text-sm font-medium text-[var(--ink)]">Draft Content.md</h4><p className="text-xs text-[var(--muted)]">Generated by Muse</p></div>
                                <SecondaryButton size="sm">Open</SecondaryButton>
                            </div>
                            <div className="p-4 flex items-center gap-3 hover:bg-[var(--canvas)] transition-colors cursor-pointer">
                                <div className="p-2 bg-[var(--canvas)] text-[var(--muted)] rounded-[var(--radius-sm)]"><Link size={18} /></div>
                                <div className="flex-1"><h4 className="text-sm font-medium text-[var(--ink)]">Reference URL</h4><p className="text-xs text-[var(--muted)]">Competitor post analysis</p></div>
                            </div>
                        </div>
                    </BlueprintCard>

                    <section>
                        <h3 className="font-technical text-[var(--muted)] mb-3">ACTIVITY</h3>
                        <div className="space-y-4 border-l border-[var(--border-subtle)] pl-4">
                            <div className="relative">
                                <div className="absolute -left-[21px] top-1.5 w-2.5 h-2.5 rounded-full bg-[var(--blueprint)] border border-[var(--paper)]" />
                                <p className="text-sm text-[var(--ink)]">Move created by <strong>System</strong></p>
                                <p className="text-xs text-[var(--muted)]">2 days ago</p>
                            </div>
                            <div className="relative">
                                <div className="absolute -left-[21px] top-1.5 w-2.5 h-2.5 rounded-full bg-[var(--border)] border border-[var(--paper)]" />
                                <p className="text-sm text-[var(--ink)]">Status updated to <strong>Active</strong></p>
                                <p className="text-xs text-[var(--muted)]">Yesterday</p>
                            </div>
                        </div>
                    </section>
                </div>

                {/* Sidebar */}
                <div className="space-y-6">
                    <BlueprintCard title="Details" code="META" padding="md" showCorners>
                        <div className="space-y-4">
                            <div><span className="text-xs font-technical text-[var(--muted)] block mb-1">ASSIGNEE</span><div className="flex items-center gap-2"><div className="w-6 h-6 rounded-full bg-[var(--ink)] text-[var(--paper)] flex items-center justify-center text-xs font-bold">AR</div><span className="text-sm text-[var(--ink)]">Alex Rivera</span></div></div>
                            <div><span className="text-xs font-technical text-[var(--muted)] block mb-1">DUE DATE</span><span className="text-sm text-[var(--ink)]">Jan 24, 2024</span></div>
                            <div><span className="text-xs font-technical text-[var(--muted)] block mb-1">CAMPAIGN</span><span className="text-sm text-[var(--blueprint)] hover:underline cursor-pointer">Q1 Growth</span></div>
                        </div>
                    </BlueprintCard>

                    <BlueprintCard code="TIMER" padding="md" className="bg-[var(--canvas)]">
                        <div className="flex items-center justify-between mb-2">
                            <span className="text-xs font-technical text-[var(--muted)]">TIME TRACKED</span>
                            <span className="font-mono text-sm text-[var(--ink)]">00:45:12</span>
                        </div>
                        <div className="flex gap-2">
                            <button className="flex-1 flex items-center justify-center gap-2 h-8 rounded-[var(--radius-sm)] bg-[var(--blueprint)] text-[var(--paper)] text-xs font-medium"><Play size={12} /> Start</button>
                            <button className="flex-1 flex items-center justify-center gap-2 h-8 rounded-[var(--radius-sm)] border border-[var(--border)] text-[var(--ink)] text-xs font-medium"><StopCircle size={12} /> Log</button>
                        </div>
                    </BlueprintCard>
                </div>
            </div>
        </div>
    );
}
