export interface FrontendEnv {
  NEXT_PUBLIC_APP_URL: string;
  NEXT_PUBLIC_API_BASE_URL: string;
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string;
  NEXT_PUBLIC_CLERK_SIGN_IN_URL?: string;
  NEXT_PUBLIC_CLERK_SIGN_UP_URL?: string;
  NEXT_PUBLIC_SENTRY_DSN: string;
}

export interface BackendEnv {
  APP_ENV: string;
  AWS_REGION: string;
  RAPTORFLOW_BIND_ADDR: string;
  RAPTORFLOW_FRONTEND_URL: string;
  RAPTORFLOW_DATABASE_URL: string;
  RAPTORFLOW_DIRECT_DATABASE_URL: string;
  RAPTORFLOW_QDRANT_URL: string;
  RAPTORFLOW_QDRANT_API_KEY: string;
  QDRANT_URL: string;
  QDRANT_API_KEY: string;
  DATABASE_URL: string;
  DIRECT_DATABASE_URL: string;
  PRISMA_ACCELERATE_URL: string;
  PRISMA_PULSE_API_KEY: string;
  RAPTORFLOW_S3_BUCKET: string;
  RAPTORFLOW_SQS_BASE_URL: string;
  RAPTORFLOW_SQS_EMBEDDING_QUEUE: string;
  RAPTORFLOW_SQS_CONTENT_QUEUE: string;
  RAPTORFLOW_CLERK_ISSUER: string;
  RAPTORFLOW_CLERK_JWKS_URL: string;
  RAPTORFLOW_CLERK_AUDIENCE: string;
  RAPTORFLOW_CLERK_WEBHOOK_SECRET: string;
  RAPTORFLOW_SENTRY_DSN: string;
  SENTRY_DSN: string;
  SENTRY_AUTH_TOKEN: string;
  SENTRY_ORG: string;
  SENTRY_PROJECT: string;
  RAPTORFLOW_BEDROCK_REGION: string;
  RAPTORFLOW_BEDROCK_MODEL_STRATEGIST: string;
  RAPTORFLOW_BEDROCK_MODEL_FAST: string;
  RAPTORFLOW_RAZORPAY_KEY_ID: string;
  RAPTORFLOW_RAZORPAY_KEY_SECRET: string;
  RAPTORFLOW_RAZORPAY_WEBHOOK_SECRET: string;
  RAPTORFLOW_WEBHOOK_TIMESTAMP_TOLERANCE_SECONDS: string;
  RAPTORFLOW_RESEND_API_KEY: string;
  RAPTORFLOW_RESEND_FROM_EMAIL: string;
  RAPTORFLOW_RESEND_WEBHOOK_SECRET: string;
}
