export interface FrontendEnv {
  NEXT_PUBLIC_APP_URL: string;
  NEXT_PUBLIC_API_BASE_URL: string;
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string;
}

export interface BackendEnv {
  RAPTORFLOW_BIND_ADDR: string;
  RAPTORFLOW_DATABASE_URL: string;
  RAPTORFLOW_DIRECT_DATABASE_URL: string;
  RAPTORFLOW_DRAGONFLY_URL: string;
  RAPTORFLOW_QDRANT_URL: string;
  RAPTORFLOW_S3_BUCKET: string;
  RAPTORFLOW_SQS_EMBEDDING_QUEUE: string;
  RAPTORFLOW_SQS_CONTENT_QUEUE: string;
  RAPTORFLOW_GCP_API_KEY: string;
  RAPTORFLOW_CLERK_JWKS_URL: string;
  RAPTORFLOW_SENTRY_DSN: string;
}
