/**
 * PDF Generator Service
 *
 * Creates beautiful, professionally formatted PDFs using Puppeteer.
 * Supports templates, branding, and high-quality output.
 */

import puppeteer, { Browser, Page, PDFOptions } from 'puppeteer';
import handlebars from 'handlebars';
import path from 'path';
import fs from 'fs/promises';
import { s3Connector } from './s3Connector';
import { env } from '../config/env';

// Register Handlebars helpers
handlebars.registerHelper('eq', (a, b) => a === b);
handlebars.registerHelper('ne', (a, b) => a !== b);
handlebars.registerHelper('gt', (a, b) => a > b);
handlebars.registerHelper('lt', (a, b) => a < b);
handlebars.registerHelper('and', (a, b) => a && b);
handlebars.registerHelper('or', (a, b) => a || b);
handlebars.registerHelper('not', (a) => !a);
handlebars.registerHelper('formatDate', (date, format) => {
  if (!date) return '';
  const d = new Date(date);
  return d.toLocaleDateString('en-US', format || {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
});
handlebars.registerHelper('json', (obj) => JSON.stringify(obj, null, 2));
handlebars.registerHelper('truncate', (str, len) => {
  if (!str) return '';
  return str.length > len ? str.substring(0, len) + '...' : str;
});
handlebars.registerHelper('capitalize', (str) => {
  if (!str) return '';
  return str.charAt(0).toUpperCase() + str.slice(1);
});
handlebars.registerHelper('join', (arr, sep) => {
  if (!Array.isArray(arr)) return '';
  return arr.join(sep || ', ');
});
handlebars.registerHelper('split', (str, sep) => {
  if (!str) return [];
  return str.split(sep || ' ');
});
handlebars.registerHelper('multiply', (a, b) => {
  return (a || 0) * (b || 1);
});
handlebars.registerHelper('@indexPlusOne', function(options) {
  return options.data.index + 1;
});
handlebars.registerHelper('platformIcon', (platform) => {
  const icons: Record<string, string> = {
    instagram: '📸',
    twitter: '🐦',
    facebook: '👥',
    linkedin: '💼',
    tiktok: '🎵',
    youtube: '📺',
    pinterest: '📌'
  };
  return icons[platform?.toLowerCase()] || '📱';
});

export interface PDFTemplate {
  name: string;
  html: string;
  css?: string;
  defaultOptions?: Partial<PDFOptions>;
}

export interface PDFGenerationOptions {
  template: string;
  data: Record<string, any>;
  options?: PDFOptions;
  filename?: string;
  bucket?: string;
  metadata?: Record<string, string>;
  brandProfile?: any; // For dynamic branding
}

export interface BrandStyling {
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  textColor: string;
  backgroundColor: string;
  fontFamily: string;
  logoUrl?: string;
}

export interface PDFResult {
  filename: string;
  key: string;
  url: string;
  size: number;
  template: string;
  generatedAt: string;
}

class PDFGeneratorService {
  private browser: Browser | null = null;
  private templates: Map<string, PDFTemplate> = new Map();

  constructor() {
    this.initializeTemplates();
    this.registerPartials();
  }

  /**
   * Register Handlebars partials for reusable components
   */
  private registerPartials(): void {
    // Header partial
    handlebars.registerPartial('header', `
      <header class="pdf-header">
        {{#if logoUrl}}
        <div class="logo-container">
          <img src="{{logoUrl}}" alt="{{brandName}} Logo" class="logo" />
        </div>
        {{/if}}
        <div class="header-content">
          <h1 class="main-title">{{title}}</h1>
          {{#if subtitle}}
          <p class="subtitle">{{subtitle}}</p>
          {{/if}}
        </div>
        <div class="header-meta">
          <div class="meta-item">
            <span class="meta-label">Generated</span>
            <span class="meta-value">{{generatedDate}}</span>
          </div>
          {{#if brandName}}
          <div class="meta-item">
            <span class="meta-label">Brand</span>
            <span class="meta-value">{{brandName}}</span>
          </div>
          {{/if}}
        </div>
      </header>
    `);

    // Footer partial
    handlebars.registerPartial('footer', `
      <footer class="pdf-footer">
        <div class="footer-content">
          <p class="footer-text">Generated by Muse AI Agents</p>
          {{#if version}}
          <p class="version">v{{version}}</p>
          {{/if}}
        </div>
        <div class="footer-decoration">
          <div class="decoration-line"></div>
        </div>
      </footer>
    `);

    // Section header partial
    handlebars.registerPartial('section-header', `
      <div class="section-header">
        <h2 class="section-title">{{title}}</h2>
        {{#if description}}
        <p class="section-description">{{description}}</p>
        {{/if}}
      </div>
    `);

    // Card partial
    handlebars.registerPartial('card', `
      <div class="card {{#if class}}{{class}}{{/if}}">
        {{#if title}}
        <div class="card-header">
          <h3 class="card-title">{{title}}</h3>
          {{#if badge}}
          <span class="card-badge {{badge.type}}">{{badge.text}}</span>
          {{/if}}
        </div>
        {{/if}}
        <div class="card-content">
          {{{content}}}
        </div>
        {{#if footer}}
        <div class="card-footer">
          {{{footer}}}
        </div>
        {{/if}}
      </div>
    `);
  }

  /**
   * Extract brand styling from brand profile
   */
  private extractBrandStyling(brandProfile?: any): BrandStyling {
    const defaultStyling: BrandStyling = {
      primaryColor: '#2563eb',
      secondaryColor: '#64748b',
      accentColor: '#f59e0b',
      textColor: '#1f2937',
      backgroundColor: '#ffffff',
      fontFamily: "'Inter', 'Helvetica Neue', Arial, sans-serif",
    };

    if (!brandProfile) return defaultStyling;

    // Extract colors from brand profile
    const colors = brandProfile.colors || brandProfile.brandColors || {};
    const primaryColor = colors.primary || colors.brand || defaultStyling.primaryColor;
    const secondaryColor = colors.secondary || colors.accent || defaultStyling.secondaryColor;
    const accentColor = colors.accent || colors.highlight || defaultStyling.accentColor;

    return {
      primaryColor,
      secondaryColor,
      accentColor,
      textColor: colors.text || defaultStyling.textColor,
      backgroundColor: colors.background || defaultStyling.backgroundColor,
      fontFamily: brandProfile.fontFamily || defaultStyling.fontFamily,
      logoUrl: brandProfile.logoUrl || brandProfile.logo,
    };
  }

  /**
   * Generate dynamic CSS based on brand styling
   */
  private generateBrandCSS(styling: BrandStyling, baseCSS: string): string {
    const brandVariables = `
      :root {
        --brand-primary: ${styling.primaryColor};
        --brand-secondary: ${styling.secondaryColor};
        --brand-accent: ${styling.accentColor};
        --brand-text: ${styling.textColor};
        --brand-background: ${styling.backgroundColor};
        --brand-font-family: ${styling.fontFamily};
        --brand-primary-light: ${this.lightenColor(styling.primaryColor, 0.2)};
        --brand-primary-dark: ${this.darkenColor(styling.primaryColor, 0.2)};
        --brand-secondary-light: ${this.lightenColor(styling.secondaryColor, 0.1)};
      }
    `;

    // Replace color placeholders in CSS
    let brandedCSS = baseCSS
      .replace(/#2563eb/g, 'var(--brand-primary)')  // Primary blue
      .replace(/#64748b/g, 'var(--brand-secondary)') // Secondary gray
      .replace(/#f59e0b/g, 'var(--brand-accent)')     // Accent amber
      .replace(/#1f2937/g, 'var(--brand-text)')      // Text color
      .replace(/#ffffff/g, 'var(--brand-background)') // Background
      .replace(/'Helvetica Neue', Arial, sans-serif/g, 'var(--brand-font-family)');

    return brandVariables + '\n\n' + brandedCSS;
  }

  /**
   * Lighten a hex color
   */
  private lightenColor(hex: string, percent: number): string {
    const num = parseInt(hex.replace("#", ""), 16);
    const amt = Math.round(2.55 * percent * 100);
    const R = (num >> 16) + amt;
    const G = (num >> 8 & 0x00FF) + amt;
    const B = (num & 0x0000FF) + amt;
    return "#" + (0x1000000 + (R < 255 ? R < 1 ? 0 : R : 255) * 0x10000 +
      (G < 255 ? G < 1 ? 0 : G : 255) * 0x100 +
      (B < 255 ? B < 1 ? 0 : B : 255)).toString(16).slice(1);
  }

  /**
   * Darken a hex color
   */
  private darkenColor(hex: string, percent: number): string {
    const num = parseInt(hex.replace("#", ""), 16);
    const amt = Math.round(2.55 * percent * 100);
    const R = (num >> 16) - amt;
    const G = (num >> 8 & 0x00FF) - amt;
    const B = (num & 0x0000FF) - amt;
    return "#" + (0x1000000 + (R > 255 ? 255 : R < 0 ? 0 : R) * 0x10000 +
      (G > 255 ? 255 : G < 0 ? 0 : G) * 0x100 +
      (B > 255 ? 255 : B < 0 ? 0 : B)).toString(16).slice(1);
  }

  /**
   * Initialize PDF templates
   */
  private async initializeTemplates(): Promise<void> {
    // Professional Brand Script PDF Template
    this.templates.set('brand-script', {
      name: 'Professional Brand Script',
      html: `
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>{{title}} - {{brandName}}</title>
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
          <style>
            {{css}}
          </style>
        </head>
        <body>
          {{> header}}

          <main class="main-content">
            <!-- Hero Section -->
            <section class="hero-section">
              <div class="hero-content">
                <h1 class="hero-title">Brand Storytelling Script</h1>
                <p class="hero-subtitle">A compelling narrative crafted for {{brandName}}</p>
                <div class="hero-stats">
                  <div class="stat-item">
                    <span class="stat-number">{{wordCount}}</span>
                    <span class="stat-label">Words</span>
                  </div>
                  <div class="stat-item">
                    <span class="stat-number">{{readingTime}}</span>
                    <span class="stat-label">Min Read</span>
                  </div>
                  <div class="stat-item">
                    <span class="stat-number">{{tone}}</span>
                    <span class="stat-label">Tone</span>
                  </div>
                </div>
              </div>
            </section>

            <!-- Script Content -->
            <section class="script-section">
              {{> section-header title="The Script" description="Your brand's authentic voice and story"}}
              <div class="script-content">
                <div class="script-text">{{{script}}}</div>
              </div>
            </section>

            <!-- Key Messages -->
            {{#if keyMessages}}
            <section class="messages-section">
              {{> section-header title="Key Messages" description="Core communications to remember"}}
              <div class="messages-grid">
                {{#each keyMessages}}
                <div class="message-card">
                  <div class="message-icon">💡</div>
                  <div class="message-content">
                    <p>{{this}}</p>
                  </div>
                </div>
                {{/each}}
              </div>
            </section>
            {{/if}}

            <!-- Script Analysis -->
            <section class="analysis-section">
              {{> section-header title="Script Analysis" description="Technical breakdown and recommendations"}}
              <div class="analysis-grid">
                <div class="analysis-card">
                  <h4>Content Metrics</h4>
                  <div class="metric">
                    <span class="metric-label">Word Count:</span>
                    <span class="metric-value">{{wordCount}}</span>
                  </div>
                  <div class="metric">
                    <span class="metric-label">Reading Time:</span>
                    <span class="metric-value">{{readingTime}} minutes</span>
                  </div>
                  <div class="metric">
                    <span class="metric-label">Sections:</span>
                    <span class="metric-value">{{sections.length}}</span>
                  </div>
                </div>

                <div class="analysis-card">
                  <h4>Style & Tone</h4>
                  <div class="metric">
                    <span class="metric-label">Tone:</span>
                    <span class="metric-value">{{tone}}</span>
                  </div>
                  <div class="metric">
                    <span class="metric-label">Voice:</span>
                    <span class="metric-value">{{voice}}</span>
                  </div>
                  <div class="metric">
                    <span class="metric-label">Target Audience:</span>
                    <span class="metric-value">{{targetAudience}}</span>
                  </div>
                </div>

                <div class="analysis-card">
                  <h4>Performance</h4>
                  <div class="metric">
                    <span class="metric-label">Engagement Score:</span>
                    <span class="metric-value">{{engagementScore}}/10</span>
                  </div>
                  <div class="metric">
                    <span class="metric-label">Clarity Score:</span>
                    <span class="metric-value">{{clarityScore}}/10</span>
                  </div>
                  <div class="metric">
                    <span class="metric-label">Brand Alignment:</span>
                    <span class="metric-value">{{brandAlignment}}/10</span>
                  </div>
                </div>
              </div>
            </section>

            <!-- Script Sections (if detailed) -->
            {{#if sections}}
            <section class="sections-breakdown">
              {{> section-header title="Section Breakdown" description="Detailed analysis of script components"}}
              <div class="sections-container">
                {{#each sections}}
                <div class="section-item">
                  <div class="section-header">
                    <h4>{{heading}}</h4>
                    <span class="section-purpose">{{purpose}}</span>
                  </div>
                  <div class="section-content">
                    <p>{{content}}</p>
                  </div>
                </div>
                {{/each}}
              </div>
            </section>
            {{/if}}

            <!-- Recommendations -->
            <section class="recommendations-section">
              {{> section-header title="Recommendations" description="How to use this script effectively"}}
              <div class="recommendations-grid">
                <div class="recommendation-card">
                  <div class="rec-icon">🎯</div>
                  <h4>Delivery Tips</h4>
                  <ul>
                    <li>Speak with confidence and natural pace</li>
                    <li>Pause at key emotional moments</li>
                    <li>Make eye contact with your audience</li>
                    <li>Practice pronunciation of key terms</li>
                  </ul>
                </div>

                <div class="recommendation-card">
                  <div class="rec-icon">📊</div>
                  <h4>Usage Guidelines</h4>
                  <ul>
                    <li>Adapt length based on platform/time constraints</li>
                    <li>Maintain core message integrity</li>
                    <li>Test different delivery styles</li>
                    <li>Measure audience engagement metrics</li>
                  </ul>
                </div>

                <div class="recommendation-card">
                  <div class="rec-icon">🔄</div>
                  <h4>Next Steps</h4>
                  <ul>
                    <li>Record and review performance</li>
                    <li>Gather audience feedback</li>
                    <li>Refine based on analytics</li>
                    <li>Create variations for different contexts</li>
                  </ul>
                </div>
              </div>
            </section>
          </main>

          {{> footer}}
        </body>
        </html>
      `,
      css: `
        /* CSS Variables for Dynamic Branding */
        :root {
          --brand-primary: #2563eb;
          --brand-secondary: #64748b;
          --brand-accent: #f59e0b;
          --brand-text: #1f2937;
          --brand-background: #ffffff;
          --brand-font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
          --shadow-sm: 0 1px 2px 0 rgb(0 0 0 / 0.05);
          --shadow-md: 0 4px 6px -1px rgb(0 0 0 / 0.1);
          --shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1);
          --border-radius: 8px;
          --border-radius-lg: 12px;
        }

        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }

        body {
          font-family: var(--brand-font-family);
          font-size: 14px;
          line-height: 1.6;
          color: var(--brand-text);
          background: var(--brand-background);
          -webkit-font-smoothing: antialiased;
          -moz-osx-font-smoothing: grayscale;
        }

        /* Header Styles */
        .pdf-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 40px 0 30px;
          border-bottom: 2px solid var(--brand-primary);
          margin-bottom: 40px;
          gap: 20px;
        }

        .logo-container {
          flex-shrink: 0;
        }

        .logo {
          height: 60px;
          width: auto;
          object-fit: contain;
        }

        .header-content {
          flex: 1;
          text-align: center;
        }

        .main-title {
          font-size: 32px;
          font-weight: 700;
          color: var(--brand-text);
          margin-bottom: 8px;
          letter-spacing: -0.025em;
        }

        .subtitle {
          font-size: 18px;
          color: var(--brand-secondary);
          font-weight: 400;
        }

        .header-meta {
          flex-shrink: 0;
          text-align: right;
        }

        .meta-item {
          display: block;
          margin-bottom: 4px;
        }

        .meta-label {
          font-size: 11px;
          color: var(--brand-secondary);
          text-transform: uppercase;
          letter-spacing: 0.05em;
          font-weight: 500;
        }

        .meta-value {
          font-size: 13px;
          color: var(--brand-text);
          font-weight: 600;
        }

        /* Main Content */
        .main-content {
          max-width: none;
        }

        /* Hero Section */
        .hero-section {
          background: linear-gradient(135deg, var(--brand-primary) 0%, var(--brand-primary-light) 100%);
          color: white;
          padding: 60px 0;
          margin: -40px -40px 40px -40px;
          border-radius: var(--border-radius-lg);
        }

        .hero-content {
          max-width: 800px;
          margin: 0 auto;
          text-align: center;
          padding: 0 40px;
        }

        .hero-title {
          font-size: 48px;
          font-weight: 700;
          margin-bottom: 16px;
          letter-spacing: -0.025em;
        }

        .hero-subtitle {
          font-size: 20px;
          opacity: 0.9;
          margin-bottom: 40px;
        }

        .hero-stats {
          display: flex;
          justify-content: center;
          gap: 40px;
        }

        .stat-item {
          text-align: center;
        }

        .stat-number {
          display: block;
          font-size: 36px;
          font-weight: 700;
          margin-bottom: 4px;
        }

        .stat-label {
          font-size: 14px;
          opacity: 0.8;
          text-transform: uppercase;
          letter-spacing: 0.05em;
        }

        /* Section Headers */
        .section-header {
          margin-bottom: 30px;
        }

        .section-title {
          font-size: 28px;
          font-weight: 600;
          color: var(--brand-text);
          margin-bottom: 8px;
          border-left: 4px solid var(--brand-primary);
          padding-left: 20px;
        }

        .section-description {
          font-size: 16px;
          color: var(--brand-secondary);
          padding-left: 24px;
        }

        /* Script Content */
        .script-content {
          background: #fafbfc;
          border: 1px solid #e1e5e9;
          border-radius: var(--border-radius-lg);
          padding: 40px;
          margin: 20px 0;
          position: relative;
        }

        .script-content:before {
          content: '"';
          position: absolute;
          top: 20px;
          left: 30px;
          font-size: 60px;
          color: var(--brand-primary);
          opacity: 0.1;
          font-family: Georgia, serif;
        }

        .script-text {
          font-size: 18px;
          line-height: 1.8;
          color: var(--brand-text);
          font-weight: 400;
          text-align: justify;
          hyphens: auto;
        }

        /* Messages Grid */
        .messages-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
          gap: 20px;
          margin: 20px 0;
        }

        .message-card {
          background: white;
          border: 1px solid #e1e5e9;
          border-radius: var(--border-radius);
          padding: 24px;
          box-shadow: var(--shadow-sm);
          transition: box-shadow 0.2s ease;
        }

        .message-icon {
          font-size: 24px;
          margin-bottom: 12px;
        }

        .message-content p {
          font-size: 16px;
          line-height: 1.6;
          color: var(--brand-text);
        }

        /* Analysis Grid */
        .analysis-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
          gap: 24px;
          margin: 20px 0;
        }

        .analysis-card {
          background: white;
          border: 1px solid #e1e5e9;
          border-radius: var(--border-radius);
          padding: 24px;
          box-shadow: var(--shadow-sm);
        }

        .analysis-card h4 {
          font-size: 18px;
          font-weight: 600;
          color: var(--brand-text);
          margin-bottom: 16px;
          border-bottom: 2px solid var(--brand-primary);
          padding-bottom: 8px;
        }

        .metric {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 8px 0;
          border-bottom: 1px solid #f1f5f9;
        }

        .metric:last-child {
          border-bottom: none;
        }

        .metric-label {
          font-weight: 500;
          color: var(--brand-secondary);
        }

        .metric-value {
          font-weight: 600;
          color: var(--brand-text);
        }

        /* Sections Breakdown */
        .sections-container {
          display: flex;
          flex-direction: column;
          gap: 24px;
        }

        .section-item {
          background: white;
          border: 1px solid #e1e5e9;
          border-radius: var(--border-radius);
          padding: 24px;
          box-shadow: var(--shadow-sm);
        }

        .section-item .section-header {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          margin-bottom: 16px;
          padding-bottom: 12px;
          border-bottom: 1px solid #e1e5e9;
        }

        .section-item h4 {
          font-size: 20px;
          font-weight: 600;
          color: var(--brand-text);
          margin: 0;
        }

        .section-purpose {
          font-size: 12px;
          color: var(--brand-secondary);
          background: #f1f5f9;
          padding: 4px 8px;
          border-radius: 12px;
          text-transform: uppercase;
          letter-spacing: 0.05em;
          font-weight: 500;
        }

        .section-content p {
          font-size: 16px;
          line-height: 1.7;
          color: var(--brand-text);
        }

        /* Recommendations */
        .recommendations-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
          gap: 24px;
          margin: 20px 0;
        }

        .recommendation-card {
          background: white;
          border: 1px solid #e1e5e9;
          border-radius: var(--border-radius);
          padding: 24px;
          text-align: center;
          box-shadow: var(--shadow-sm);
          transition: transform 0.2s ease;
        }

        .recommendation-card:hover {
          transform: translateY(-2px);
        }

        .rec-icon {
          font-size: 32px;
          margin-bottom: 16px;
        }

        .recommendation-card h4 {
          font-size: 18px;
          font-weight: 600;
          color: var(--brand-text);
          margin-bottom: 16px;
        }

        .recommendation-card ul {
          list-style: none;
          padding: 0;
          text-align: left;
        }

        .recommendation-card li {
          padding: 6px 0;
          font-size: 14px;
          color: var(--brand-secondary);
          position: relative;
          padding-left: 20px;
        }

        .recommendation-card li:before {
          content: "✓";
          color: var(--brand-primary);
          font-weight: bold;
          position: absolute;
          left: 0;
        }

        /* Footer */
        .pdf-footer {
          margin-top: 60px;
          padding-top: 30px;
          border-top: 1px solid #e1e5e9;
        }

        .footer-content {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 20px;
        }

        .footer-text {
          font-size: 12px;
          color: var(--brand-secondary);
        }

        .version {
          font-size: 11px;
          color: var(--brand-secondary);
          background: #f1f5f9;
          padding: 2px 6px;
          border-radius: 8px;
        }

        .footer-decoration {
          text-align: center;
        }

        .decoration-line {
          height: 2px;
          background: linear-gradient(90deg, transparent 0%, var(--brand-primary) 50%, transparent 100%);
          border-radius: 1px;
        }

        /* Print Styles */
        @media print {
          body {
            font-size: 12px;
          }

          .hero-section {
            margin: 0 !important;
            padding: 30px 0;
            border-radius: 0;
            -webkit-print-color-adjust: exact;
          }

          .recommendation-card {
            break-inside: avoid;
          }

          .message-card,
          .analysis-card,
          .section-item {
            break-inside: avoid;
          }
        }

        /* Responsive Design */
        @media (max-width: 768px) {
          .hero-stats {
            flex-direction: column;
            gap: 20px;
          }

          .analysis-grid,
          .recommendations-grid,
          .messages-grid {
            grid-template-columns: 1fr;
          }

          .pdf-header {
            flex-direction: column;
            text-align: center;
            gap: 20px;
          }

          .header-meta {
            text-align: center;
          }
        }
      `,
      defaultOptions: {
        format: 'A4',
        margin: {
          top: '1cm',
          right: '1cm',
          bottom: '1cm',
          left: '1cm',
        },
        printBackground: true,
        preferCSSPageSize: true,
      },
    });

    // Professional Social Media Campaign PDF Template
    this.templates.set('social-media-ideas', {
      name: 'Professional Social Media Campaign',
      html: `
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>{{brandName}} - Social Media Campaign Strategy</title>
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
          <style>
            {{css}}
          </style>
        </head>
        <body>
          {{> header title="Social Media Campaign Strategy" subtitle="Comprehensive content strategy for maximum engagement"}}

          <main class="main-content">
            <!-- Campaign Hero -->
            <section class="campaign-hero">
              <div class="hero-background">
                <div class="hero-pattern"></div>
              </div>
              <div class="hero-content">
                <div class="campaign-badge">
                  <span class="badge-icon">🚀</span>
                  <span class="badge-text">Campaign Ready</span>
                </div>
                <h1 class="campaign-title">{{campaignTheme}}</h1>
                <p class="campaign-description">A data-driven social media strategy designed to maximize engagement and drive results for {{brandName}}.</p>

                <div class="campaign-metrics">
                  <div class="metric">
                    <span class="metric-number">{{ideas.length}}</span>
                    <span class="metric-label">Content Ideas</span>
                  </div>
                  <div class="metric">
                    <span class="metric-number">{{platforms.length}}</span>
                    <span class="metric-label">Platforms</span>
                  </div>
                  <div class="metric">
                    <span class="metric-number">{{totalEngagement}}</span>
                    <span class="metric-label">Est. Engagement</span>
                  </div>
                </div>
              </div>
            </section>

            <!-- Campaign Overview -->
            <section class="overview-section">
              {{> section-header title="Campaign Overview" description="Strategic foundation and key objectives"}}
              <div class="overview-cards">
                <div class="overview-card">
                  <div class="card-icon">🎯</div>
                  <h3>Objectives</h3>
                  <ul>
                    {{#each objectives}}
                    <li>{{this}}</li>
                    {{/each}}
                  </ul>
                </div>

                <div class="overview-card">
                  <div class="card-icon">👥</div>
                  <h3>Target Audience</h3>
                  <p>{{targetAudience}}</p>
                  <div class="audience-stats">
                    <span class="stat">Age: {{audienceAge}}</span>
                    <span class="stat">Interests: {{audienceInterests}}</span>
                  </div>
                </div>

                <div class="overview-card">
                  <div class="card-icon">📊</div>
                  <h3>Platform Strategy</h3>
                  <div class="platform-list">
                    {{#each platforms}}
                    <span class="platform-tag">{{this}}</span>
                    {{/each}}
                  </div>
                  <p class="platform-note">Optimized for each platform's unique audience and format requirements.</p>
                </div>
              </div>
            </section>

            <!-- Content Ideas Showcase -->
            <section class="content-showcase">
              {{> section-header title="Content Ideas Portfolio" description="Curated content concepts with performance predictions"}}
              <div class="content-grid">
                {{#each ideas}}
                <div class="content-card" data-platform="{{platform}}">
                  <div class="content-header">
                    <div class="platform-badge {{platform}}">
                      <span class="platform-icon">{{platformIcon platform}}</span>
                      <span class="platform-name">{{platform}}</span>
                    </div>
                    <div class="content-type">{{contentType}}</div>
                  </div>

                  <div class="content-body">
                    <h4 class="content-title">{{idea}}</h4>
                    <div class="engagement-score">
                      <div class="score-bar">
                        <div class="score-fill" style="width: {{multiply engagement 10}}%"></div>
                      </div>
                      <span class="score-text">{{engagement}}/10 Engagement</span>
                    </div>

                    {{#if caption}}
                    <div class="content-caption">
                      <h5>Caption</h5>
                      <p>{{caption}}</p>
                    </div>
                    {{/if}}

                    {{#if hashtags}}
                    <div class="content-hashtags">
                      <h5>Hashtags</h5>
                      <div class="hashtag-tags">
                        {{#each (split hashtags ' ')}}
                        <span class="hashtag">{{this}}</span>
                        {{/each}}
                      </div>
                    </div>
                    {{/if}}

                    <div class="content-timing">
                      <div class="timing-item">
                        <span class="timing-icon">🕐</span>
                        <span class="timing-text">{{timing}}</span>
                      </div>
                      <div class="timing-item">
                        <span class="timing-icon">📈</span>
                        <span class="timing-text">{{estimatedReach}} reach</span>
                      </div>
                    </div>
                  </div>

                  <div class="content-footer">
                    <div class="performance-prediction">
                      <span class="prediction-label">Predicted Performance:</span>
                      <div class="prediction-metrics">
                        <span class="metric">❤️ {{likes}}</span>
                        <span class="metric">💬 {{comments}}</span>
                        <span class="metric">↗️ {{shares}}</span>
                      </div>
                    </div>
                  </div>
                </div>
                {{/each}}
              </div>
            </section>

            <!-- Content Calendar -->
            {{#if contentCalendar}}
            <section class="calendar-section">
              {{> section-header title="Content Calendar" description="30-day content rollout plan"}}
              <div class="calendar-container">
                <div class="calendar-header">
                  <h3>Monthly Content Schedule</h3>
                  <p>Strategic content distribution across platforms</p>
                </div>

                <table class="content-calendar">
                  <thead>
                    <tr>
                      <th>Date</th>
                      <th>Platform</th>
                      <th>Content Type</th>
                      <th>Theme</th>
                      <th>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {{#each contentCalendar}}
                    <tr>
                      <td class="date-cell">{{formatDate date}}</td>
                      <td class="platform-cell">
                        <span class="platform-indicator {{platform}}">{{platformIcon platform}}</span>
                        {{platform}}
                      </td>
                      <td class="type-cell">{{contentType}}</td>
                      <td class="theme-cell">{{theme}}</td>
                      <td class="status-cell">
                        <span class="status-badge {{status}}">{{status}}</span>
                      </td>
                    </tr>
                    {{/each}}
                  </tbody>
                </table>
              </div>
            </section>
            {{/if}}

            <!-- Performance Dashboard -->
            <section class="performance-section">
              {{> section-header title="Performance Dashboard" description="Expected campaign metrics and KPIs"}}
              <div class="performance-grid">
                <div class="performance-card">
                  <h4>Engagement Metrics</h4>
                  <div class="metric-chart">
                    <div class="chart-bar">
                      <div class="bar-fill likes" style="height: 75%"></div>
                      <span class="bar-label">Likes</span>
                    </div>
                    <div class="chart-bar">
                      <div class="bar-fill comments" style="height: 60%"></div>
                      <span class="bar-label">Comments</span>
                    </div>
                    <div class="chart-bar">
                      <div class="bar-fill shares" style="height: 45%"></div>
                      <span class="bar-label">Shares</span>
                    </div>
                    <div class="chart-bar">
                      <div class="bar-fill saves" style="height: 30%"></div>
                      <span class="bar-label">Saves</span>
                    </div>
                  </div>
                </div>

                <div class="performance-card">
                  <h4>Growth Projections</h4>
                  <div class="growth-timeline">
                    <div class="timeline-item">
                      <span class="timeline-date">Week 1-2</span>
                      <span class="timeline-metric">+{{week1Followers}} followers</span>
                    </div>
                    <div class="timeline-item">
                      <span class="timeline-date">Week 3-4</span>
                      <span class="timeline-metric">+{{week2Followers}} followers</span>
                    </div>
                    <div class="timeline-item">
                      <span class="timeline-date">Month 1</span>
                      <span class="timeline-metric">{{month1Engagement}}% engagement</span>
                    </div>
                  </div>
                </div>

                <div class="performance-card">
                  <h4>Success Metrics</h4>
                  <div class="success-indicators">
                    {{#each successMetrics}}
                    <div class="indicator">
                      <div class="indicator-icon">{{icon}}</div>
                      <div class="indicator-content">
                        <h5>{{title}}</h5>
                        <p>{{description}}</p>
                        <span class="target">Target: {{target}}</span>
                      </div>
                    </div>
                    {{/each}}
                  </div>
                </div>
              </div>
            </section>

            <!-- Implementation Guide -->
            <section class="implementation-section">
              {{> section-header title="Implementation Guide" description="Step-by-step execution strategy"}}
              <div class="implementation-steps">
                {{#each implementationSteps}}
                <div class="step-card">
                  <div class="step-number">{{@indexPlusOne}}</div>
                  <div class="step-content">
                    <h4>{{title}}</h4>
                    <p>{{description}}</p>
                    {{#if tools}}
                    <div class="step-tools">
                      <strong>Tools needed:</strong> {{join tools ', '}}
                    </div>
                    {{/if}}
                    {{#if timeline}}
                    <div class="step-timeline">{{timeline}}</div>
                    {{/if}}
                  </div>
                </div>
                {{/each}}
              </div>
            </section>
          </main>

          {{> footer}}
        </body>
        </html>
      `,
      css: `
        /* CSS Variables for Dynamic Branding */
        :root {
          --brand-primary: #e11d48;
          --brand-secondary: #64748b;
          --brand-accent: #f59e0b;
          --brand-text: #1f2937;
          --brand-background: #ffffff;
          --brand-font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
          --shadow-sm: 0 1px 2px 0 rgb(0 0 0 / 0.05);
          --shadow-md: 0 4px 6px -1px rgb(0 0 0 / 0.1);
          --shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1);
          --border-radius: 8px;
          --border-radius-lg: 12px;
        }

        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }

        body {
          font-family: var(--brand-font-family);
          font-size: 14px;
          line-height: 1.6;
          color: var(--brand-text);
          background: var(--brand-background);
          -webkit-font-smoothing: antialiased;
          -moz-osx-font-smoothing: grayscale;
        }

        /* Header Styles */
        .pdf-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 40px 0 30px;
          border-bottom: 2px solid var(--brand-primary);
          margin-bottom: 40px;
          gap: 20px;
        }

        .logo-container {
          flex-shrink: 0;
        }

        .logo {
          height: 60px;
          width: auto;
          object-fit: contain;
        }

        .header-content {
          flex: 1;
          text-align: center;
        }

        .main-title {
          font-size: 32px;
          font-weight: 700;
          color: var(--brand-text);
          margin-bottom: 8px;
          letter-spacing: -0.025em;
        }

        .subtitle {
          font-size: 18px;
          color: var(--brand-secondary);
          font-weight: 400;
        }

        .header-meta {
          flex-shrink: 0;
          text-align: right;
        }

        .meta-item {
          display: block;
          margin-bottom: 4px;
        }

        .meta-label {
          font-size: 11px;
          color: var(--brand-secondary);
          text-transform: uppercase;
          letter-spacing: 0.05em;
          font-weight: 500;
        }

        .meta-value {
          font-size: 13px;
          color: var(--brand-text);
          font-weight: 600;
        }

        /* Campaign Hero */
        .campaign-hero {
          position: relative;
          background: linear-gradient(135deg, var(--brand-primary) 0%, #ffffff 100%);
          border-radius: var(--border-radius-lg);
          margin: 0 0 40px 0;
          overflow: hidden;
          min-height: 300px;
        }

        .hero-background {
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          opacity: 0.05;
        }

        .hero-pattern {
          width: 100%;
          height: 100%;
          background-image:
            radial-gradient(circle at 20% 80%, var(--brand-primary) 0%, transparent 50%),
            radial-gradient(circle at 80% 20%, var(--brand-accent) 0%, transparent 50%);
        }

        .hero-content {
          position: relative;
          z-index: 2;
          padding: 40px;
          text-align: center;
          color: var(--brand-text);
        }

        .campaign-badge {
          display: inline-flex;
          align-items: center;
          gap: 8px;
          background: rgba(255, 255, 255, 0.9);
          padding: 8px 16px;
          border-radius: 20px;
          margin-bottom: 20px;
          font-size: 14px;
          font-weight: 600;
          color: var(--brand-primary);
        }

        .campaign-title {
          font-size: 42px;
          font-weight: 700;
          margin-bottom: 16px;
          letter-spacing: -0.025em;
        }

        .campaign-description {
          font-size: 18px;
          opacity: 0.8;
          margin-bottom: 30px;
          max-width: 600px;
          margin-left: auto;
          margin-right: auto;
        }

        .campaign-metrics {
          display: flex;
          justify-content: center;
          gap: 40px;
        }

        .metric {
          text-align: center;
        }

        .metric-number {
          display: block;
          font-size: 32px;
          font-weight: 700;
          color: var(--brand-primary);
          margin-bottom: 4px;
        }

        .metric-label {
          font-size: 14px;
          opacity: 0.7;
          text-transform: uppercase;
          letter-spacing: 0.05em;
        }

        /* Section Headers */
        .section-header {
          margin-bottom: 30px;
        }

        .section-title {
          font-size: 28px;
          font-weight: 600;
          color: var(--brand-text);
          margin-bottom: 8px;
          border-left: 4px solid var(--brand-primary);
          padding-left: 20px;
        }

        .section-description {
          font-size: 16px;
          color: var(--brand-secondary);
          padding-left: 24px;
        }

        /* Overview Cards */
        .overview-cards {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
          gap: 24px;
          margin: 20px 0;
        }

        .overview-card {
          background: white;
          border: 1px solid #e1e5e9;
          border-radius: var(--border-radius);
          padding: 24px;
          box-shadow: var(--shadow-sm);
        }

        .card-icon {
          font-size: 32px;
          margin-bottom: 16px;
        }

        .overview-card h3 {
          font-size: 20px;
          font-weight: 600;
          color: var(--brand-text);
          margin-bottom: 16px;
        }

        .overview-card ul {
          list-style: none;
          padding: 0;
        }

        .overview-card li {
          padding: 6px 0;
          font-size: 14px;
          color: var(--brand-secondary);
          position: relative;
          padding-left: 20px;
        }

        .overview-card li:before {
          content: "✓";
          color: var(--brand-primary);
          font-weight: bold;
          position: absolute;
          left: 0;
        }

        .audience-stats {
          margin-top: 12px;
          display: flex;
          flex-wrap: wrap;
          gap: 8px;
        }

        .stat {
          font-size: 12px;
          background: #f1f5f9;
          padding: 4px 8px;
          border-radius: 12px;
          color: var(--brand-secondary);
        }

        .platform-list {
          display: flex;
          flex-wrap: wrap;
          gap: 8px;
          margin-bottom: 12px;
        }

        .platform-tag {
          background: var(--brand-primary);
          color: white;
          padding: 4px 12px;
          border-radius: 16px;
          font-size: 12px;
          font-weight: 500;
        }

        /* Content Grid */
        .content-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
          gap: 24px;
          margin: 20px 0;
        }

        .content-card {
          background: white;
          border: 1px solid #e1e5e9;
          border-radius: var(--border-radius);
          overflow: hidden;
          box-shadow: var(--shadow-sm);
          transition: transform 0.2s ease;
        }

        .content-card:hover {
          transform: translateY(-2px);
        }

        .content-header {
          background: var(--brand-primary);
          color: white;
          padding: 16px 20px;
          display: flex;
          justify-content: space-between;
          align-items: center;
        }

        .platform-badge {
          display: flex;
          align-items: center;
          gap: 8px;
          font-size: 14px;
          font-weight: 600;
        }

        .platform-icon {
          font-size: 16px;
        }

        .content-type {
          background: rgba(255, 255, 255, 0.2);
          padding: 4px 8px;
          border-radius: 12px;
          font-size: 12px;
          font-weight: 500;
        }

        .content-body {
          padding: 20px;
        }

        .content-title {
          font-size: 18px;
          font-weight: 600;
          color: var(--brand-text);
          margin-bottom: 16px;
          line-height: 1.4;
        }

        .engagement-score {
          margin-bottom: 20px;
        }

        .score-bar {
          background: #e1e5e9;
          height: 8px;
          border-radius: 4px;
          margin-bottom: 8px;
          overflow: hidden;
        }

        .score-fill {
          height: 100%;
          background: linear-gradient(90deg, var(--brand-primary), var(--brand-accent));
          border-radius: 4px;
        }

        .score-text {
          font-size: 12px;
          font-weight: 600;
          color: var(--brand-secondary);
        }

        .content-caption,
        .content-hashtags {
          margin-bottom: 16px;
        }

        .content-caption h5,
        .content-hashtags h5 {
          font-size: 14px;
          font-weight: 600;
          color: var(--brand-text);
          margin-bottom: 8px;
          text-transform: uppercase;
          letter-spacing: 0.05em;
        }

        .content-caption p {
          font-size: 14px;
          line-height: 1.6;
          color: var(--brand-secondary);
          font-style: italic;
        }

        .hashtag-tags {
          display: flex;
          flex-wrap: wrap;
          gap: 6px;
        }

        .hashtag {
          background: #f1f5f9;
          color: var(--brand-primary);
          padding: 4px 8px;
          border-radius: 12px;
          font-size: 12px;
          font-weight: 500;
        }

        .content-timing {
          display: flex;
          gap: 16px;
          margin-top: 16px;
        }

        .timing-item {
          display: flex;
          align-items: center;
          gap: 6px;
          font-size: 13px;
          color: var(--brand-secondary);
        }

        .content-footer {
          background: #f8fafc;
          padding: 16px 20px;
          border-top: 1px solid #e1e5e9;
        }

        .performance-prediction {
          display: flex;
          justify-content: space-between;
          align-items: center;
        }

        .prediction-label {
          font-size: 12px;
          color: var(--brand-secondary);
          font-weight: 500;
        }

        .prediction-metrics {
          display: flex;
          gap: 12px;
        }

        .metric {
          font-size: 12px;
          font-weight: 600;
          color: var(--brand-text);
        }

        /* Calendar */
        .calendar-container {
          background: white;
          border: 1px solid #e1e5e9;
          border-radius: var(--border-radius);
          overflow: hidden;
          box-shadow: var(--shadow-sm);
          margin: 20px 0;
        }

        .calendar-header {
          background: var(--brand-primary);
          color: white;
          padding: 20px;
        }

        .calendar-header h3 {
          font-size: 20px;
          font-weight: 600;
          margin-bottom: 4px;
        }

        .calendar-header p {
          font-size: 14px;
          opacity: 0.9;
        }

        .content-calendar {
          width: 100%;
          border-collapse: collapse;
        }

        .content-calendar th,
        .content-calendar td {
          padding: 16px 20px;
          text-align: left;
          border-bottom: 1px solid #e1e5e9;
        }

        .content-calendar th {
          background: #f8fafc;
          font-weight: 600;
          color: var(--brand-text);
          font-size: 13px;
          text-transform: uppercase;
          letter-spacing: 0.05em;
        }

        .date-cell {
          font-weight: 600;
          color: var(--brand-primary);
        }

        .platform-cell {
          display: flex;
          align-items: center;
          gap: 8px;
        }

        .platform-indicator {
          width: 24px;
          height: 24px;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 12px;
        }

        .status-badge {
          padding: 4px 8px;
          border-radius: 12px;
          font-size: 11px;
          font-weight: 600;
          text-transform: uppercase;
          letter-spacing: 0.05em;
        }

        .status-badge.scheduled {
          background: #dbeafe;
          color: #1d4ed8;
        }

        .status-badge.published {
          background: #dcfce7;
          color: #166534;
        }

        .status-badge.draft {
          background: #fef3c7;
          color: #92400e;
        }

        /* Performance Dashboard */
        .performance-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
          gap: 24px;
          margin: 20px 0;
        }

        .performance-card {
          background: white;
          border: 1px solid #e1e5e9;
          border-radius: var(--border-radius);
          padding: 24px;
          box-shadow: var(--shadow-sm);
        }

        .performance-card h4 {
          font-size: 18px;
          font-weight: 600;
          color: var(--brand-text);
          margin-bottom: 20px;
          border-bottom: 2px solid var(--brand-primary);
          padding-bottom: 8px;
        }

        .metric-chart {
          display: flex;
          gap: 16px;
          align-items: end;
          height: 120px;
        }

        .chart-bar {
          flex: 1;
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 8px;
        }

        .bar-fill {
          width: 100%;
          background: linear-gradient(180deg, var(--brand-primary), var(--brand-primary-dark));
          border-radius: 4px 4px 0 0;
          min-height: 20px;
        }

        .bar-fill.likes { background: linear-gradient(180deg, #e11d48, #be123c); }
        .bar-fill.comments { background: linear-gradient(180deg, #2563eb, #1d4ed8); }
        .bar-fill.shares { background: linear-gradient(180deg, #16a34a, #15803d); }
        .bar-fill.saves { background: linear-gradient(180deg, #f59e0b, #d97706); }

        .bar-label {
          font-size: 12px;
          font-weight: 500;
          color: var(--brand-secondary);
        }

        .growth-timeline {
          display: flex;
          flex-direction: column;
          gap: 12px;
        }

        .timeline-item {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 12px 0;
          border-bottom: 1px solid #e1e5e9;
        }

        .timeline-date {
          font-weight: 600;
          color: var(--brand-text);
        }

        .timeline-metric {
          color: var(--brand-primary);
          font-weight: 500;
        }

        .success-indicators {
          display: flex;
          flex-direction: column;
          gap: 16px;
        }

        .indicator {
          display: flex;
          gap: 12px;
          align-items: flex-start;
        }

        .indicator-icon {
          font-size: 24px;
          flex-shrink: 0;
        }

        .indicator-content h5 {
          font-size: 16px;
          font-weight: 600;
          color: var(--brand-text);
          margin-bottom: 4px;
        }

        .indicator-content p {
          font-size: 14px;
          color: var(--brand-secondary);
          margin-bottom: 6px;
        }

        .target {
          font-size: 12px;
          color: var(--brand-primary);
          font-weight: 500;
        }

        /* Implementation Steps */
        .implementation-steps {
          display: flex;
          flex-direction: column;
          gap: 20px;
        }

        .step-card {
          display: flex;
          gap: 20px;
          background: white;
          border: 1px solid #e1e5e9;
          border-radius: var(--border-radius);
          padding: 24px;
          box-shadow: var(--shadow-sm);
        }

        .step-number {
          width: 40px;
          height: 40px;
          background: var(--brand-primary);
          color: white;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 18px;
          font-weight: 700;
          flex-shrink: 0;
        }

        .step-content h4 {
          font-size: 18px;
          font-weight: 600;
          color: var(--brand-text);
          margin-bottom: 8px;
        }

        .step-content p {
          font-size: 14px;
          color: var(--brand-secondary);
          margin-bottom: 12px;
        }

        .step-tools,
        .step-timeline {
          font-size: 13px;
          color: var(--brand-secondary);
        }

        .step-tools strong,
        .step-timeline strong {
          color: var(--brand-text);
        }

        /* Footer */
        .pdf-footer {
          margin-top: 60px;
          padding-top: 30px;
          border-top: 1px solid #e1e5e9;
        }

        .footer-content {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 20px;
        }

        .footer-text {
          font-size: 12px;
          color: var(--brand-secondary);
        }

        .version {
          font-size: 11px;
          color: var(--brand-secondary);
          background: #f1f5f9;
          padding: 2px 6px;
          border-radius: 8px;
        }

        .footer-decoration {
          text-align: center;
        }

        .decoration-line {
          height: 2px;
          background: linear-gradient(90deg, transparent 0%, var(--brand-primary) 50%, transparent 100%);
          border-radius: 1px;
        }

        /* Platform-specific colors */
        .platform-badge.instagram { background: linear-gradient(45deg, #f09433, #e6683c, #dc2743, #cc2366, #bc1888); }
        .platform-badge.twitter { background: #1da1f2; }
        .platform-badge.facebook { background: #1877f2; }
        .platform-badge.linkedin { background: #0077b5; }
        .platform-badge.tiktok { background: linear-gradient(45deg, #000000, #ff0050); }
        .platform-badge.youtube { background: #ff0000; }
        .platform-badge.pinterest { background: #e60023; }

        .platform-indicator.instagram { background: linear-gradient(45deg, #f09433, #e6683c); }
        .platform-indicator.twitter { background: #1da1f2; }
        .platform-indicator.facebook { background: #1877f2; }
        .platform-indicator.linkedin { background: #0077b5; }
        .platform-indicator.tiktok { background: linear-gradient(45deg, #000000, #ff0050); }
        .platform-indicator.youtube { background: #ff0000; }
        .platform-indicator.pinterest { background: #e60023; }

        /* Print Styles */
        @media print {
          .content-card {
            break-inside: avoid;
          }

          .step-card {
            break-inside: avoid;
          }

          .campaign-hero {
            -webkit-print-color-adjust: exact;
          }
        }

        /* Responsive Design */
        @media (max-width: 768px) {
          .campaign-metrics {
            flex-direction: column;
            gap: 20px;
          }

          .content-grid {
            grid-template-columns: 1fr;
          }

          .overview-cards {
            grid-template-columns: 1fr;
          }

          .performance-grid {
            grid-template-columns: 1fr;
          }

          .content-header {
            flex-direction: column;
            gap: 12px;
            align-items: flex-start;
          }

          .step-card {
            flex-direction: column;
            gap: 16px;
            text-align: center;
          }

          .platform-cell {
            flex-direction: column;
            gap: 4px;
          }
        }
      `,
      defaultOptions: {
        format: 'A4',
        margin: {
          top: '1cm',
          right: '1cm',
          bottom: '1cm',
          left: '1cm',
        },
        printBackground: true,
        preferCSSPageSize: true,
      },
    });

    // Professional Tagline Collection Template
    this.templates.set('tagline-collection', {
      name: 'Professional Tagline Collection',
      html: `
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Brand Taglines - {{brandName}}</title>
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
          <style>
            {{css}}
          </style>
        </head>
        <body>
          {{> header title="Brand Tagline Collection" subtitle="Memorable messaging crafted for impact"}}

          <main class="main-content">
            <!-- Tagline Hero -->
            <section class="tagline-hero">
              <div class="hero-content">
                <h1 class="tagline-main">"{{primaryTagline}}"</h1>
                <p class="tagline-description">Your primary brand tagline, designed to capture attention and communicate value instantly.</p>
                <div class="tagline-metrics">
                  <div class="metric">
                    <span class="metric-number">{{brandAlignment}}/10</span>
                    <span class="metric-label">Brand Alignment</span>
                  </div>
                  <div class="metric">
                    <span class="metric-number">{{memorability}}/10</span>
                    <span class="metric-label">Memorability</span>
                  </div>
                  <div class="metric">
                    <span class="metric-number">{{uniqueness}}/10</span>
                    <span class="metric-label">Uniqueness</span>
                  </div>
                </div>
              </div>
            </section>

            <!-- Alternative Taglines -->
            {{#if alternativeTaglines}}
            <section class="alternatives-section">
              {{> section-header title="Alternative Taglines" description="Additional options for different contexts and campaigns"}}
              <div class="taglines-grid">
                {{#each alternativeTaglines}}
                <div class="tagline-card">
                  <div class="tagline-quote">"{{this}}"</div>
                  <div class="tagline-meta">
                    <span class="tagline-number">Option {{@indexPlusOne}}</span>
                  </div>
                </div>
                {{/each}}
              </div>
            </section>
            {{/if}}

            <!-- Usage Guidelines -->
            <section class="guidelines-section">
              {{> section-header title="Usage Guidelines" description="How to implement these taglines effectively"}}
              <div class="guidelines-grid">
                <div class="guideline-card">
                  <div class="guideline-icon">📢</div>
                  <h4>Brand Communications</h4>
                  <ul>
                    <li>Use primary tagline on website hero section</li>
                    <li>Include in email signatures and business cards</li>
                    <li>Feature prominently in marketing materials</li>
                    <li>Display on social media profile headers</li>
                  </ul>
                </div>

                <div class="guideline-card">
                  <div class="guideline-icon">🎨</div>
                  <h4>Visual Guidelines</h4>
                  <ul>
                    <li>Pair with brand colors and typography</li>
                    <li>Use appropriate hierarchy in layouts</li>
                    <li>Ensure readability across all mediums</li>
                    <li>Maintain consistent spacing and alignment</li>
                  </ul>
                </div>
              </div>
            </section>
          </main>

          {{> footer}}
        </body>
        </html>
      `,
      css: `
        :root {
          --brand-primary: #2563eb;
          --brand-secondary: #64748b;
          --brand-accent: #f59e0b;
          --brand-text: #1f2937;
          --brand-background: #ffffff;
          --brand-font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
        }

        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
          font-family: var(--brand-font-family);
          font-size: 14px;
          line-height: 1.6;
          color: var(--brand-text);
          background: var(--brand-background);
        }

        .pdf-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 40px 0 30px;
          border-bottom: 2px solid var(--brand-primary);
          margin-bottom: 40px;
          gap: 20px;
        }

        .main-title {
          font-size: 32px;
          font-weight: 700;
          color: var(--brand-text);
          margin-bottom: 8px;
        }

        .subtitle {
          font-size: 18px;
          color: var(--brand-secondary);
        }

        .header-meta {
          text-align: right;
          font-size: 13px;
          color: var(--brand-secondary);
        }

        .tagline-hero {
          background: linear-gradient(135deg, var(--brand-primary) 0%, #ffffff 100%);
          padding: 60px 0;
          margin: 0 0 40px 0;
          border-radius: 12px;
          text-align: center;
        }

        .tagline-main {
          font-size: 48px;
          font-weight: 700;
          color: var(--brand-text);
          margin-bottom: 20px;
          line-height: 1.2;
        }

        .tagline-description {
          font-size: 18px;
          color: var(--brand-secondary);
          margin-bottom: 40px;
          max-width: 600px;
          margin-left: auto;
          margin-right: auto;
        }

        .tagline-metrics {
          display: flex;
          justify-content: center;
          gap: 40px;
        }

        .metric-number {
          display: block;
          font-size: 32px;
          font-weight: 700;
          color: var(--brand-primary);
        }

        .metric-label {
          font-size: 14px;
          color: var(--brand-secondary);
          text-transform: uppercase;
          letter-spacing: 0.05em;
        }

        .section-title {
          font-size: 28px;
          font-weight: 600;
          color: var(--brand-text);
          margin-bottom: 8px;
          border-left: 4px solid var(--brand-primary);
          padding-left: 20px;
        }

        .section-description {
          font-size: 16px;
          color: var(--brand-secondary);
          padding-left: 24px;
        }

        .taglines-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
          gap: 24px;
          margin: 30px 0;
        }

        .tagline-card {
          background: white;
          border: 1px solid #e1e5e9;
          border-radius: 12px;
          padding: 32px;
          text-align: center;
          box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1);
        }

        .tagline-quote {
          font-size: 24px;
          font-weight: 600;
          color: var(--brand-text);
          margin-bottom: 20px;
          line-height: 1.3;
        }

        .tagline-number {
          font-size: 12px;
          color: var(--brand-secondary);
          text-transform: uppercase;
          letter-spacing: 0.05em;
          font-weight: 500;
        }

        .guidelines-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
          gap: 24px;
          margin: 30px 0;
        }

        .guideline-card {
          background: white;
          border: 1px solid #e1e5e9;
          border-radius: 8px;
          padding: 24px;
          text-align: center;
        }

        .guideline-icon {
          font-size: 32px;
          margin-bottom: 16px;
        }

        .guideline-card h4 {
          font-size: 18px;
          font-weight: 600;
          color: var(--brand-text);
          margin-bottom: 16px;
        }

        .guideline-card ul {
          list-style: none;
          padding: 0;
          text-align: left;
        }

        .guideline-card li {
          padding: 6px 0;
          font-size: 14px;
          color: var(--brand-secondary);
          position: relative;
          padding-left: 20px;
        }

        .guideline-card li:before {
          content: "✓";
          color: var(--brand-primary);
          font-weight: bold;
          position: absolute;
          left: 0;
        }

        .pdf-footer {
          margin-top: 60px;
          padding-top: 30px;
          border-top: 1px solid #e1e5e9;
          text-align: center;
        }

        .footer-text {
          font-size: 12px;
          color: var(--brand-secondary);
          margin-bottom: 10px;
        }

        .version {
          font-size: 11px;
          background: #f1f5f9;
          padding: 2px 6px;
          border-radius: 8px;
        }

        @media print {
          .tagline-card { break-inside: avoid; }
        }

        @media (max-width: 768px) {
          .taglines-grid, .guidelines-grid {
            grid-template-columns: 1fr;
          }
          .tagline-metrics {
            flex-direction: column;
            gap: 20px;
          }
        }
      `,
      defaultOptions: {
        format: 'A4',
        margin: {
          top: '1cm',
          right: '1cm',
          bottom: '1cm',
          left: '1cm',
        },
        printBackground: true,
        preferCSSPageSize: true,
      },
    });
  }

  /**
   * Generate PDF from template and data
   */
  async generatePDF(options: PDFGenerationOptions): Promise<PDFResult> {
    const { template: templateName, data, options: pdfOptions, filename, metadata, brandProfile } = options;

    const template = this.templates.get(templateName);
    if (!template) {
      throw new Error(`Template '${templateName}' not found`);
    }

    const browser = await this.getBrowser();
    const page = await browser.newPage();

    try {
      // Extract brand styling
      const brandStyling = this.extractBrandStyling(brandProfile);

      // Prepare template data with brand information
      const templateData = {
        ...data,
        generatedDate: new Date().toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'long',
          day: 'numeric',
        }),
        generatedAt: new Date().toISOString(),
        brandName: brandProfile?.name || brandProfile?.brandName || 'Your Brand',
        logoUrl: brandStyling.logoUrl,
        version: '2.0.0',
      };

      // Compile and render HTML with brand styling
      const compiledTemplate = handlebars.compile(template.html);
      const html = compiledTemplate(templateData);

      // Generate branded CSS
      const brandedCSS = this.generateBrandCSS(brandStyling, template.css);

      // Combine HTML with branded CSS
      const fullHTML = html.replace('{{css}}', brandedCSS);

      // Set content with proper options for modern web features
      await page.setContent(fullHTML, {
        waitUntil: 'networkidle0',
        timeout: 30000
      });

      // Wait for fonts to load
      await page.waitForTimeout(1000);

      // Generate PDF with high quality settings
      const finalOptions: PDFOptions = {
        ...template.defaultOptions,
        ...pdfOptions,
        // Ensure high quality output
        printBackground: true,
        preferCSSPageSize: true,
        displayHeaderFooter: false,
      };

      const pdfBuffer = await page.pdf(finalOptions);

      // Generate filename and S3 key
      const finalFilename = filename || this.generateFilename(templateName, templateData);
      const s3Key = `pdfs/${Date.now()}_${finalFilename}`;

      // Upload to S3 with enhanced metadata
      const uploadResult = await s3Connector.uploadFile(s3Key, pdfBuffer, {
        contentType: 'application/pdf',
        metadata: {
          ...metadata,
          template: templateName,
          generatedAt: new Date().toISOString(),
          fileSize: pdfBuffer.length.toString(),
          brandName: templateData.brandName,
          version: templateData.version,
          generator: 'Muse AI PDF Generator',
        },
      });

      const result: PDFResult = {
        filename: finalFilename,
        key: s3Key,
        url: uploadResult.location,
        size: uploadResult.size,
        template: templateName,
        generatedAt: new Date().toISOString(),
      };

      console.log(`🎨 Generated premium PDF: ${finalFilename} (${pdfBuffer.length} bytes) for ${templateData.brandName}`);

      return result;

    } finally {
      await page.close();
    }
  }

  /**
   * Generate PDF for brand script
   */
  async generateBrandScriptPDF(
    scriptData: any,
    brandProfile: any
  ): Promise<PDFResult> {
    // Enhance script data with analysis
    const enhancedData = {
      ...scriptData,
      title: scriptData.title || 'Brand Storytelling Script',
      wordCount: this.countWords(scriptData.script || ''),
      readingTime: Math.ceil(this.countWords(scriptData.script || '') / 200), // ~200 words per minute
      sections: scriptData.sections || [],
      keyMessages: scriptData.keyMessages || [],
      tone: scriptData.tone || 'Professional',
      voice: scriptData.voice || 'Confident',
      targetAudience: scriptData.targetAudience || 'General Audience',
      engagementScore: scriptData.engagementScore || 8.5,
      clarityScore: scriptData.clarityScore || 9.0,
      brandAlignment: scriptData.brandAlignment || 9.5,
    };

    return this.generatePDF({
      template: 'brand-script',
      data: enhancedData,
      brandProfile,
      filename: `brand-storytelling-script-${Date.now()}.pdf`,
      metadata: {
        type: 'brand-script',
        brandId: brandProfile?.id,
        contentType: 'brand-storytelling',
        aiGenerated: 'true',
      },
    });
  }

  /**
   * Generate PDF for social media campaign
   */
  async generateSocialMediaPDF(
    campaignData: any,
    brandProfile: any
  ): Promise<PDFResult> {
    // Enhance campaign data with comprehensive information
    const enhancedData = {
      ...campaignData,
      campaignTheme: campaignData.campaignTheme || 'Brand Awareness Campaign',
      ideas: campaignData.ideas || [],
      platforms: this.extractUniquePlatforms(campaignData.ideas || []),
      totalEngagement: this.calculateTotalEngagement(campaignData.ideas || []),
      objectives: campaignData.objectives || [
        'Increase brand awareness',
        'Drive website traffic',
        'Boost engagement rates'
      ],
      targetAudience: campaignData.targetAudience || '18-35 year olds interested in lifestyle',
      audienceAge: campaignData.audienceAge || '25-34',
      audienceInterests: campaignData.audienceInterests || 'Technology, Design, Lifestyle',
      contentCalendar: campaignData.contentCalendar || [],
      successMetrics: campaignData.successMetrics || [
        { title: 'Engagement Rate', description: 'Likes, comments, shares per post', target: '>5%', icon: '📈' },
        { title: 'Reach Growth', description: 'New audience reached', target: '+25%', icon: '👥' },
        { title: 'Website Traffic', description: 'Clicks to website', target: '+30%', icon: '🌐' }
      ],
      implementationSteps: campaignData.implementationSteps || [
        {
          title: 'Content Creation',
          description: 'Create all content pieces according to the campaign calendar',
          tools: ['Canva', 'Adobe Creative Suite', 'Mobile Camera'],
          timeline: 'Week 1-2'
        },
        {
          title: 'Scheduling & Posting',
          description: 'Schedule posts using platform tools or third-party schedulers',
          tools: ['Buffer', 'Hootsuite', 'Platform native schedulers'],
          timeline: 'Week 3-4'
        },
        {
          title: 'Monitoring & Engagement',
          description: 'Monitor performance and engage with audience comments',
          tools: ['Google Analytics', 'Platform Insights', 'Social Mention'],
          timeline: 'Ongoing'
        }
      ],
      week1Followers: campaignData.week1Followers || '500-1000',
      week2Followers: campaignData.week2Followers || '800-1500',
      month1Engagement: campaignData.month1Engagement || '4.2',
    };

    return this.generatePDF({
      template: 'social-media-ideas',
      data: enhancedData,
      brandProfile,
      filename: `social-media-campaign-strategy-${Date.now()}.pdf`,
      metadata: {
        type: 'social-media-campaign',
        brandId: brandProfile?.id,
        contentType: 'marketing-strategy',
        aiGenerated: 'true',
        platforms: enhancedData.platforms.join(','),
      },
    });
  }

  /**
   * Generate PDF for tagline collection
   */
  async generateTaglinePDF(
    taglineData: any,
    brandProfile: any
  ): Promise<PDFResult> {
    // Enhance tagline data with analysis
    const enhancedData = {
      ...taglineData,
      brandValues: brandProfile?.brandValues?.join(', ') || 'innovation, quality, trust',
      industry: brandProfile?.industry || 'technology',
      targetAudience: taglineData.targetAudience || 'modern consumers',
      positioning: taglineData.positioning || 'market leader',
    };

    return this.generatePDF({
      template: 'tagline-collection',
      data: enhancedData,
      brandProfile,
      filename: `brand-taglines-${Date.now()}.pdf`,
      metadata: {
        type: 'tagline-collection',
        brandId: brandProfile?.id,
        contentType: 'brand-messaging',
        aiGenerated: 'true',
      },
    });
  }

  /**
   * Add custom template
   */
  addTemplate(name: string, template: PDFTemplate): void {
    this.templates.set(name, template);
  }

  /**
   * Get available templates
   */
  getAvailableTemplates(): string[] {
    return Array.from(this.templates.keys());
  }

  // =====================================================
  // UTILITY METHODS
  // =====================================================

  /**
   * Count words in text
   */
  private countWords(text: string): number {
    if (!text) return 0;
    return text.trim().split(/\s+/).length;
  }

  /**
   * Extract unique platforms from ideas
   */
  private extractUniquePlatforms(ideas: any[]): string[] {
    const platforms = new Set<string>();
    ideas.forEach(idea => {
      if (idea.platform) {
        platforms.add(idea.platform.toLowerCase());
      }
    });
    return Array.from(platforms);
  }

  /**
   * Calculate total engagement score
   */
  private calculateTotalEngagement(ideas: any[]): number {
    if (ideas.length === 0) return 0;
    const totalScore = ideas.reduce((sum, idea) => sum + (idea.engagement || 0), 0);
    return Math.round((totalScore / ideas.length) * 10) / 10;
  }

  /**
   * Health check
   */
  async healthCheck(): Promise<boolean> {
    try {
      const browser = await this.getBrowser();
      await browser.version();
      return true;
    } catch (error) {
      console.error('PDF generator health check failed:', error);
      return false;
    }
  }

  // =====================================================
  // PRIVATE METHODS
  // =====================================================

  private async getBrowser(): Promise<Browser> {
    if (!this.browser || this.browser.isConnected() === false) {
      this.browser = await puppeteer.launch({
        headless: true,
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--disable-accelerated-2d-canvas',
          '--no-first-run',
          '--no-zygote',
          '--single-process',
          '--disable-gpu',
        ],
      });
    }
    return this.browser;
  }

  private generateFilename(templateName: string, data: any): string {
    const timestamp = new Date().toISOString().slice(0, 19).replace(/:/g, '-');
    const brandName = data.brandName ? data.brandName.toLowerCase().replace(/[^a-z0-9]/g, '-') : 'brand';
    return `${templateName}-${brandName}-${timestamp}.pdf`;
  }

  /**
   * Cleanup resources
   */
  async cleanup(): Promise<void> {
    if (this.browser) {
      await this.browser.close();
      this.browser = null;
    }
  }
}

// Export singleton instance
export const pdfGenerator = new PDFGeneratorService();

// Handle graceful shutdown
process.on('SIGTERM', async () => {
  await pdfGenerator.cleanup();
});

process.on('SIGINT', async () => {
  await pdfGenerator.cleanup();
});

// Export types
export type { PDFTemplate, PDFGenerationOptions, PDFResult };
