"""
Pydantic models for RaptorFlow backend.
"""

from backend.models.base import BaseSchema
from backend.models.onboarding import (
    OnboardingProfile,
    OnboardingSession,
    OnboardingAnswer,
    PersonaInput,
    Goal,
    Constraints,
    ChannelFootprint,
    BusinessProfile,
    PersonalBrandProfile,
    ExecutiveBrandProfile,
    AgencyProfile,
    StylePreferences,
)

from backend.models.persona import (
    TAG_OPTIONS,
    TagWithConfidence,
    ICPProfile,
    ICPRequest,
    ICPResponse,
    Cohort,
    Demographics,
    Psychographics,
    Communication,
    PersonaNarrative,
    PersonaNarrativeRequest,
    PersonaNarrativeResponse,
    TagEnrichmentRequest,
    TagEnrichmentResponse,
    PainPointMiningRequest,
    PainPointMiningResponse,
)

from backend.models.campaign import (
    MoveRequest,
    MoveResponse,
    MoveMetrics,
    Task,
    Sprint,
    LineOfOperation,
    AssetRequirement,
    ChecklistItem,
    TaskUpdateRequest,
    MoveDecision,
    MoveAnomaly,
)

from backend.models.content import (
    BlogRequest,
    BlogResponse,
    EmailRequest,
    EmailMessage,
    EmailResponse,
    SocialPostRequest,
    SocialPostResponse,
    ContentRequest,
    ContentResponse,
    ContentVariant,
    Hook,
    ContentApprovalRequest,
    BulkContentRequest,
    ContentCalendar,
    ContentCalendarEntry,
    AssetMetadata,
    BrandVoiceProfile,
    ContentMetadata,
)

from backend.models.agent_state import (
    BaseAgentState,
    ResearchState,
    ContentState,
    StrategyState,
    ExecutionState,
    AnalyticsState,
)

__all__ = [
    # Base
    "BaseSchema",
    # Onboarding
    "OnboardingProfile",
    "OnboardingSession",
    "OnboardingAnswer",
    "PersonaInput",
    "Goal",
    "Constraints",
    "ChannelFootprint",
    "BusinessProfile",
    "PersonalBrandProfile",
    "ExecutiveBrandProfile",
    "AgencyProfile",
    "StylePreferences",
    # Persona
    "TAG_OPTIONS",
    "TagWithConfidence",
    "ICPProfile",
    "ICPRequest",
    "ICPResponse",
    "Cohort",
    "Demographics",
    "Psychographics",
    "Communication",
    "PersonaNarrative",
    "PersonaNarrativeRequest",
    "PersonaNarrativeResponse",
    "TagEnrichmentRequest",
    "TagEnrichmentResponse",
    "PainPointMiningRequest",
    "PainPointMiningResponse",
    # Campaign
    "MoveRequest",
    "MoveResponse",
    "MoveMetrics",
    "Task",
    "Sprint",
    "LineOfOperation",
    "AssetRequirement",
    "ChecklistItem",
    "TaskUpdateRequest",
    "MoveDecision",
    "MoveAnomaly",
    # Content
    "BlogRequest",
    "BlogResponse",
    "EmailRequest",
    "EmailMessage",
    "EmailResponse",
    "SocialPostRequest",
    "SocialPostResponse",
    "ContentRequest",
    "ContentResponse",
    "ContentVariant",
    "Hook",
    "ContentApprovalRequest",
    "BulkContentRequest",
    "ContentCalendar",
    "ContentCalendarEntry",
    "AssetMetadata",
    "BrandVoiceProfile",
    "ContentMetadata",
    # Agent State
    "BaseAgentState",
    "ResearchState",
    "ContentState",
    "StrategyState",
    "ExecutionState",
    "AnalyticsState",
]
