"""
Cost Tracking Models

Pydantic models for AI agent cost tracking, including estimated costs
for all AI operations within RaptorFlow.
"""

from __future__ import annotations

from typing import Optional
from uuid import UUID
from decimal import Decimal

from pydantic import Field, field_validator

from backend.models.base import BaseSchema


class CostLog(BaseSchema):
    """
    Cost log record representing an estimated cost for an AI agent action.

    This model tracks the estimated cost of every significant AI operation
    performed by agents within RaptorFlow. The cost calculation uses a
    simple placeholder formula but can be extended with more complex
    pricing models.

    Attributes:
        workspace_id: Workspace scoping identifier for multi-tenancy
        correlation_id: Unique ID for tracking this action across workflows
        agent_name: Name or identifier of the agent performing the action
        action_name: Description of the action being performed
        input_tokens: Number of input tokens processed by the AI model
        output_tokens: Number of output tokens generated by the AI model
        estimated_cost_usd: Estimated cost in USD for this operation
    """

    workspace_id: Optional[UUID] = Field(
        None,
        description="Workspace scoping identifier for multi-tenancy",
    )
    correlation_id: UUID = Field(
        ...,
        description="Unique ID for tracking this action across workflows",
    )
    agent_name: str = Field(
        ...,
        description="Name or identifier of the agent performing the action",
    )
    action_name: str = Field(
        ...,
        description="Description of the action being performed",
    )
    input_tokens: int = Field(
        ...,
        ge=0,
        description="Number of input tokens processed by the AI model",
    )
    output_tokens: int = Field(
        ...,
        ge=0,
        description="Number of output tokens generated by the AI model",
    )
    estimated_cost_usd: Decimal = Field(
        ...,
        ge=0,
        description="Estimated cost in USD for this operation",
    )

    class Config:
        """Pydantic model configuration."""
        from_attributes = True
        json_encoders = {
            Decimal: lambda v: float(v),
        }

    @field_validator("estimated_cost_usd", mode="before")
    @classmethod
    def _validate_cost(cls, value):
        """Ensure cost is a Decimal with proper precision."""
        if isinstance(value, float):
            return Decimal(str(value))
        return value

    def calculate_cost(self) -> Decimal:
        """
        Calculate the estimated cost using the simple placeholder formula.

        This is a placeholder implementation with very cheap rates for a
        generic AI model. In production, this should be replaced with
        actual pricing from your AI provider.

        Returns:
            Estimated cost in USD
        """
        # Placeholder cost calculation: (input_tokens * 0.0000001) + (output_tokens * 0.0000003)
        # This represents a very inexpensive model for demo purposes
        input_cost = Decimal(str(self.input_tokens)) * Decimal("0.0000001")
        output_cost = Decimal(str(self.output_tokens)) * Decimal("0.0000003")
        return input_cost + output_cost

    @classmethod
    def create_log(
        cls,
        workspace_id: UUID,
        correlation_id: UUID,
        agent_name: str,
        action_name: str,
        input_tokens: int,
        output_tokens: int,
    ) -> "CostLog":
        """
        Factory method to create a cost log with automatic cost calculation.

        Args:
            workspace_id: Workspace identifier
            correlation_id: Workflow correlation ID
            agent_name: Name of the agent
            action_name: Description of the action
            input_tokens: Number of input tokens
            output_tokens: Number of output tokens

        Returns:
            CostLog instance with calculated cost
        """
        instance = cls(
            workspace_id=workspace_id,
            correlation_id=correlation_id,
            agent_name=agent_name,
            action_name=action_name,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            estimated_cost_usd=Decimal("0"),  # Will be calculated
        )
        instance.estimated_cost_usd = instance.calculate_cost()
        return instance
