/**
 * Campaigns & Moves — Core Type Definitions
 * The execution engine of RaptorFlow.
 */

// =====================================
// Campaign Types
// =====================================

/** Campaign Objectives (pick ONE per campaign) */
export type CampaignObjective =
  | 'acquire' // More leads / calls / trials
  | 'activate' // Convert leads to paying customers
  | 'convert' // Warm leads → paid
  | 'launch' // Release + create demand
  | 'proof' // Case studies, testimonials
  | 'retain' // Stop churn, boost usage
  | 'monetize' // Increase revenue from existing customers
  | 'expand' // Grow into new markets
  | 'reposition'; // Change market perception

/** Campaign Status Lifecycle */
export type CampaignStatus =
  | 'draft' // Being configured
  | 'planned' // Created but no active Move
  | 'active' // Has active/queued Moves
  | 'paused' // User paused
  | 'completed' // Finished
  | 'wrapup' // Needs review before archive
  | 'archived'; // Read-only

/** Offer/CTA types */
export type OfferType =
  | 'book_call'
  | 'start_trial'
  | 'download'
  | 'buy_now'
  | 'reply_email'
  | 'subscribe'
  | 'other';

/** Available channels */
export type ChannelType =
  | 'linkedin'
  | 'email'
  | 'instagram'
  | 'whatsapp'
  | 'cold_dms'
  | 'partnerships'
  | 'twitter';

/** Campaign timeline presets */
export type CampaignDuration = 14 | 28 | 90;

export interface Campaign {
  id: string;
  name: string;
  objective: CampaignObjective;
  cohortId?: string;
  cohortName?: string;
  offer: OfferType;
  offerDetails?: string; // e.g., calendar link
  channels: ChannelType[];
  duration: CampaignDuration;
  moveLength: 7 | 14;
  dailyEffort: 15 | 30 | 60; // minutes

  status: CampaignStatus;
  ragStatus?: RAGStatus; // RED | AMBER | GREEN
  createdAt: string;
  startedAt?: string;
  completedAt?: string;

  // Extended fields for new UI
  targetAudience?: string;
  timeline?: {
    startDate: string;
    endDate: string;
    duration: number;
  };
  metrics?: {
    primary: string;
    target: number;
    current: number;
  };
  stages?: any[]; // Move references

  strategyArc?: Record<string, unknown>; // The 90-day arc generated by AI
  auditData?: Record<string, unknown>[]; // Results from Campaign Auditor
  qualityScore?: number; // Overall strategic alignment score (0-1)

  // Wrapup data (filled when campaign ends)
  wrapup?: CampaignWrapup;
}

export interface DBCampaign {
  id: string;
  tenant_id: string;
  title: string;
  objective: string;
  status: string;
  start_date?: string;
  end_date?: string;
  arc_data?: Record<string, unknown>;
  audit_data?: {
    alignments?: Record<string, unknown>[];
    overall_score?: number;
  };
  created_at: string;
  updated_at: string;
}

export interface CampaignWrapup {
  whatWorked: string;
  whatDidnt: string;
  biggestInsight: string;
  nextRecommendation?: string;
  submittedAt: string;
}

// =====================================
// Move Types
// =====================================

/** Move Goals (micro-objectives) */
export type MoveGoal =
  | 'leads' // Capture interest
  | 'calls' // Book conversations
  | 'sales' // Close deals
  | 'proof' // Collect credibility
  | 'distribution' // Grow reach
  | 'activation'; // Get users to use product

/** Move Status (explicit user completion) */
export type MoveStatus =
  | 'draft' // Created but not started
  | 'queued' // Scheduled to start
  | 'active' // Currently running
  | 'paused' // User paused (schedule frozen)
  | 'completed' // User marked complete
  | 'abandoned'; // User abandoned

/** RAG Status (deterministic health indicator) */
export type RAGStatus = 'green' | 'amber' | 'red';

/** Outcome types for Moves */
export type OutcomeType =
  | 'replies'
  | 'leads'
  | 'calls'
  | 'signups'
  | 'sales'
  | 'retention';

/** Self-report metrics for daily check-ins */
export interface SelfReportMetrics {
  leads: number;
  replies: number;
  calls: number;
  energy: number; // 1-10
  quality: number; // 1-10
  executed: boolean; // Did you execute today?
  note?: string; // Optional learning note
  submittedAt?: string;
}

/** Move asset (generated content) */
export interface MoveAsset {
  id: string;
  title: string;
  channel: ChannelType;
  status: 'draft' | 'used' | 'variant' | 'rejected' | 'saved';
  content: string;
  createdAt: string;
  usedAt?: string;
}

/** Next action (prominent on card) */
export interface NextAction {
  label: string;
  dueDate: string;
  estimatedMinutes: number;
  taskId?: string; // Reference to checklist item
}

/** Move timebox presets */
export type MoveDuration = 7 | 14 | 28;

/** Override reasons when Move doesn't match Campaign */
export type OverrideReason = 'experiment' | 'temporary_pivot' | 'special_case';

export interface ChecklistItem {
  id: string;
  label: string;
  completed: boolean;
  group: 'setup' | 'create' | 'publish' | 'followup';
  assetLink?: string; // Link to Muse asset
  muse_prompt?: string;
  agent_id?: string;
}

export interface Move {
  id: string;
  name: string;
  goal: MoveGoal;
  channel: ChannelType;
  secondaryChannel?: ChannelType;
  duration: MoveDuration;
  dailyEffort: 15 | 30 | 60;

  description?: string;
  owner?: string;
  outcomeTarget?: string; // e.g., "10 calls booked"
  checklist: ChecklistItem[];
  assetIds: string[];

  // NEW: Actionable experiment details (like Blackbox)
  hypothesis?: string; // "If we do X, then Y will happen"
  control?: string; // Current state / what we're testing against
  variant?: string; // The specific change we're making
  success_metric?: string; // What number to track (e.g., "reply rate", "CTR")
  sample_size?: string; // e.g., "500 emails", "1000 impressions"
  action_steps?: string[]; // 3-5 specific things to DO

  status: MoveStatus;
  createdAt: string;
  startedAt?: string;
  dueDate?: string;
  completedAt?: string;
  pausedAt?: string; // When move was paused

  // Campaign linkage
  campaignId?: string;
  campaignName?: string;

  refinementData?: {
    estimated_effort?: string;
    deadline?: string;
    rationale?: string;
    [key: string]: unknown;
  };

  toolRequirements?: string[];

  // Override tracking (logged to Blackbox)
  override?: {
    reason: OverrideReason;
    originalCampaignObjective: CampaignObjective;
    loggedAt: string;
  };

  // Completion self-report (legacy)
  selfReport?: MoveSelfReport;

  // =====================================
  // NEW: Operator Dashboard Fields
  // =====================================

  // Template reference
  templateId?: string;
  templateName?: string;

  // Outcome tracking
  outcomeType?: OutcomeType;
  targetNumber?: number; // e.g., 10 (calls)
  cohortId?: string; // ICP reference
  cohortName?: string;

  // RAG status (deterministic)
  rag?: RAGStatus;
  ragReason?: string; // Mandatory explanation

  // Day tracking (calculated from startedAt)
  dayNumber?: number; // Current day in timebox

  // Self-report metrics (daily check-ins)
  confidence?: number; // 1-10
  dailyMetrics?: SelfReportMetrics[]; // History of check-ins

  // Blockers
  blockers?: string[];

  // Assets (generated content)
  assets?: MoveAsset[];

  // Next action (prominent on card)
  nextAction?: NextAction;

  // Cadence settings
  cadence?: {
    postsPerDay?: number;
    dmsPerDay?: number;
    followupsPerDay?: number;
  };
}

export interface DBMove {
  id: string;
  campaign_id: string;
  title: string;
  description: string;
  status: string;
  priority: number;
  refinement_data?: {
    estimated_effort?: string;
    deadline?: string;
    rationale?: string;
    [key: string]: unknown;
  };
  tool_requirements?: string[];
  created_at: string;
  updated_at: string;
}

export interface MoveSelfReport {
  didComplete: boolean;
  whatHappened: string;
  metrics?: {
    name: string;
    value: number;
  };
  submittedAt: string;
}

// =====================================
// State Types
// =====================================

export interface CampaignsState {
  campaigns: Campaign[];
  moves: Move[];
  activeMoveId: string | null;
}

// =====================================
// Display Helpers
// =====================================

export const OBJECTIVE_LABELS: Record<
  CampaignObjective,
  { label: string; description: string }
> = {
  acquire: { label: 'Acquire', description: 'Get more leads / calls / trials' },
  activate: {
    label: 'Activate',
    description: 'Convert leads to paying customers',
  },
  convert: { label: 'Convert', description: 'Turn warm leads into paid' },
  launch: {
    label: 'Launch',
    description: 'Release something and drive demand',
  },
  proof: {
    label: 'Proof',
    description: 'Build credibility: case studies, testimonials',
  },
  retain: { label: 'Retain', description: 'Stop churn, boost usage' },
  monetize: {
    label: 'Monetize',
    description: 'Increase revenue from existing customers',
  },
  expand: { label: 'Expand', description: 'Grow into new markets' },
  reposition: {
    label: 'Reposition',
    description: 'Change what the market believes',
  },
};

export const GOAL_LABELS: Record<
  MoveGoal,
  { label: string; description: string }
> = {
  leads: { label: 'Leads', description: 'Capture interest' },
  calls: { label: 'Calls', description: 'Book conversations' },
  sales: { label: 'Sales', description: 'Close deals' },
  proof: { label: 'Proof', description: 'Collect credibility' },
  distribution: { label: 'Distribution', description: 'Grow reach' },
  activation: {
    label: 'Activation',
    description: 'Get users to use the product',
  },
};

export const OFFER_LABELS: Record<OfferType, string> = {
  book_call: 'Book a call',
  start_trial: 'Start a trial',
  download: 'Download lead magnet',
  buy_now: 'Buy now',
  reply_email: 'Reply to email',
  subscribe: 'Subscribe',
  other: 'Other',
};

export const CHANNEL_LABELS: Record<ChannelType, string> = {
  linkedin: 'LinkedIn',
  email: 'Email',
  instagram: 'Instagram',
  whatsapp: 'WhatsApp',
  cold_dms: 'Cold DMs',
  partnerships: 'Partnerships',
  twitter: 'Twitter',
};

export const OVERRIDE_LABELS: Record<OverrideReason, string> = {
  experiment: 'Experiment',
  temporary_pivot: 'Temporary pivot',
  special_case: 'Special case',
};

// =====================================
// Goal-Objective Alignment
// =====================================

/** Which goals align well with which objectives */
export const OBJECTIVE_GOAL_ALIGNMENT: Record<CampaignObjective, MoveGoal[]> = {
  acquire: ['leads', 'calls', 'distribution'],
  activate: ['activation', 'sales'],
  convert: ['calls', 'sales'],
  launch: ['distribution', 'leads', 'sales'],
  proof: ['proof'],
  retain: ['activation'],
  monetize: ['sales'],
  expand: ['distribution', 'leads'],
  reposition: ['distribution', 'proof'],
};

/** Check if a Move goal aligns with Campaign objective */
export function isGoalAligned(
  objective: CampaignObjective,
  goal: MoveGoal
): boolean {
  return OBJECTIVE_GOAL_ALIGNMENT[objective].includes(goal);
}

// =====================================
// Council API Types
// =====================================

export interface CouncilRequest {
  type: 'move' | 'campaign';
  objective: string; // "What do you want to accomplish?" / "North Star"
  context: string; // "Context, audience, constraints"
  duration?: number;
}

export interface CouncilMoveSuggestion {
  id: string; // Temporary ID for UI
  title: string;
  description: string;
  type: 'post' | 'email' | 'dm' | 'ad' | 'event' | 'other';
  toolRequirements: string[];
  confidenceScore: number; // 0-100
  rationale: string;
}

export interface CouncilCampaignArc {
  title: string;
  objective: string;
  phases: {
    name: string;
    weeks: number[];
    focus: string;
  }[];
  milestones: string[];
}

export interface CouncilResponse {
  type: 'move' | 'campaign';

  // Common
  strategicDecree: string; // High-level strategy summary
  confidence: number;
  risks: string[];

  // Debate
  debateTranscript: {
    role: string; // e.g. "Skeptic", "Strategist"
    argument: string;
  }[];
  rejectedPaths: {
    path: string;
    reason: string;
  }[];

  // Specific
  moves?: CouncilMoveSuggestion[]; // For Move request
  campaignArc?: CouncilCampaignArc; // For Campaign request
  campaignMoves?: CouncilMoveSuggestion[]; // Proposed moves for the campaign
}
