import { Campaign, Move, ChecklistItem } from './campaigns-types';

export const initialCampaigns: Campaign[] = [
  {
    id: 'campaign-1',
    name: 'Q1 Acquisition Drive',
    objective: 'acquire',
    offer: 'book_call',
    channels: ['linkedin', 'email'],
    duration: 90,
    moveLength: 14,
    dailyEffort: 30,
    status: 'active',
    createdAt: new Date().toISOString(),
    startedAt: new Date().toISOString(),
    qualityScore: 0.85,
  },
  {
    id: 'campaign-2',
    name: 'Social Proof Builder',
    objective: 'proof',
    offer: 'other',
    channels: ['linkedin'],
    duration: 28,
    moveLength: 7,
    dailyEffort: 15,
    status: 'planned',
    createdAt: new Date().toISOString(),
    qualityScore: 0.92,
  }
];

export const initialMoves: Move[] = [
  {
    id: 'move-1',
    name: 'Launch LinkedIn Campaign',
    goal: 'calls',
    channel: 'linkedin',
    duration: 7,
    dailyEffort: 30,
    description: 'Execute targeted outreach to 50 prospects in the SaaS industry',
    outcomeTarget: '10 calls booked',
    checklist: [
      {
        id: 'check-1',
        label: 'Create outreach templates',
        completed: false,
        group: 'setup',
      },
      {
        id: 'check-2',
        label: 'Build prospect list',
        completed: false,
        group: 'setup',
      },
      {
        id: 'check-3',
        label: 'Schedule campaign',
        completed: false,
        group: 'publish',
      },
    ],
    assetIds: [],
    status: 'draft',
    createdAt: new Date().toISOString(),
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    campaignId: 'campaign-1',
    hypothesis: 'If we send personalized outreach to SaaS prospects, then we can book 10 discovery calls',
    control: 'No outreach',
    variant: 'Personalized LinkedIn messages',
    success_metric: 'Call booking rate',
    sample_size: '50 prospects',
    action_steps: ['Research prospects', 'Craft personalized messages', 'Send outreach', 'Follow up'],
  },
  {
    id: 'move-2',
    name: 'Optimize Landing Page',
    goal: 'sales',
    channel: 'email',
    duration: 14,
    dailyEffort: 30,
    description: 'Improve conversion rate on the main landing page',
    outcomeTarget: '20% increase in signups',
    checklist: [
      {
        id: 'check-4',
        label: 'Analyze current conversion metrics',
        completed: true,
        group: 'setup',
      },
      {
        id: 'check-5',
        label: 'Design new hero section',
        completed: false,
        group: 'create',
      },
      {
        id: 'check-6',
        label: 'A/B test copy variations',
        completed: false,
        group: 'publish',
      },
    ],
    assetIds: [],
    status: 'active',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    startedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    campaignId: 'campaign-1',
    hypothesis: 'If we optimize the landing page copy and design, then we can increase signup conversion by 20%',
    control: 'Current landing page',
    variant: 'New hero section with clearer value proposition',
    success_metric: 'Signup conversion rate',
    sample_size: '1000 visitors',
    action_steps: ['Analyze current metrics', 'Design new hero', 'Implement changes', 'Run A/B test'],
  },
  {
    id: 'move-3',
    name: 'Customer Success Stories',
    goal: 'leads',
    channel: 'linkedin',
    duration: 28,
    dailyEffort: 15,
    description: 'Collect and publish 3 customer testimonials',
    outcomeTarget: '3 published case studies',
    checklist: [
      {
        id: 'check-7',
        label: 'Identify happy customers',
        completed: false,
        group: 'setup',
      },
      {
        id: 'check-8',
        label: 'Conduct interviews',
        completed: false,
        group: 'create',
      },
      {
        id: 'check-9',
        label: 'Create case study content',
        completed: false,
        group: 'publish',
      },
    ],
    assetIds: [],
    status: 'draft',
    createdAt: new Date().toISOString(),
    dueDate: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
    campaignId: 'campaign-2',
    hypothesis: 'If we publish customer success stories, then we can increase trust and conversion rates',
    control: 'No social proof',
    variant: '3 detailed case studies with results',
    success_metric: 'Case study engagement rate',
    sample_size: '3 customers',
    action_steps: ['Identify customers', 'Schedule interviews', 'Write case studies', 'Publish and promote'],
  },
];
