#!/bin/bash

# Clerk setup script for RaptorFlow
# This script helps configure Clerk authentication

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}🔐 RaptorFlow Clerk Setup${NC}"
echo -e "${BLUE}===============================${NC}"
echo ""

# Check if clerk CLI is installed
if ! command -v clerk &> /dev/null; then
    echo -e "${YELLOW}⚠️  Clerk CLI not found. Installing...${NC}"
    echo ""
    echo -e "${BLUE}Please install the Clerk CLI first:${NC}"
    echo -e "  npm install -g @clerk/clerk-cli"
    echo -e "  # or"
    echo -e "  pnpm add -g @clerk/clerk-cli"
    echo ""
    echo -e "${YELLOW}After installation, run this script again.${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Clerk CLI found${NC}"
echo ""

# Check if user is logged in
echo -e "${YELLOW}Checking Clerk authentication...${NC}"
if ! clerk whoami &> /dev/null; then
    echo -e "${YELLOW}Please log in to Clerk:${NC}"
    clerk login
fi

echo -e "${GREEN}✅ Clerk authenticated${NC}"
echo ""

# Create or select project
echo -e "${BLUE}Project Setup:${NC}"
echo -e "1. Create a new Clerk application for RaptorFlow"
echo -e "2. Use existing application"
echo ""

read -p "Choose option (1/2): " choice

case $choice in
    1)
        echo ""
        echo -e "${YELLOW}Creating new Clerk application...${NC}"
        read -p "Enter application name [RaptorFlow Dev]: " app_name
        app_name=${app_name:-"RaptorFlow Dev"}

        # Create application
        clerk applications:create "$app_name"
        echo -e "${GREEN}✅ Application '$app_name' created${NC}"
        ;;

    2)
        echo ""
        echo -e "${YELLOW}Available applications:${NC}"
        clerk applications:list
        echo ""
        read -p "Enter application ID or name: " app_id
        clerk applications:select "$app_id"
        echo -e "${GREEN}✅ Application selected${NC}"
        ;;

    *)
        echo -e "${RED}❌ Invalid choice${NC}"
        exit 1
        ;;
esac

echo ""
echo -e "${BLUE}Webhook Setup:${NC}"
echo -e "Setting up webhook endpoint for user/org events..."
echo ""

# Set webhook URL (localhost for dev)
webhook_url="http://localhost:8080/api/v1/webhooks/clerk"
echo -e "${YELLOW}Setting webhook URL to: $webhook_url${NC}"

# Create webhook
webhook_secret=$(clerk webhooks:create --url "$webhook_url" --events "user.created,user.updated,organization.created,organization_membership.created,organization_membership.updated" | grep -o 'whsec_[^"]*')

if [ -z "$webhook_secret" ]; then
    echo -e "${RED}❌ Failed to create webhook. Please create it manually in the Clerk dashboard.${NC}"
    echo -e "${YELLOW}Webhook URL: $webhook_url${NC}"
    echo -e "${YELLOW}Events: user.created, user.updated, organization.created, organization_membership.created, organization_membership.updated${NC}"
    read -p "Enter webhook secret manually: " webhook_secret
fi

echo -e "${GREEN}✅ Webhook configured${NC}"

# Get application details
echo ""
echo -e "${BLUE}Retrieving application configuration...${NC}"

# Get publishable key
publishable_key=$(clerk applications:get | grep -o '"publishable_key": *"[^"]*"' | cut -d'"' -f4)

# Get API URLs
api_url=$(clerk applications:get | grep -o '"api_url": *"[^"]*"' | cut -d'"' -f4)
issuer_url=$(clerk applications:get | grep -o '"issuer_url": *"[^"]*"' | cut -d'"' -f4)

if [ -z "$publishable_key" ] || [ -z "$api_url" ] || [ -z "$issuer_url" ]; then
    echo -e "${RED}❌ Failed to retrieve application configuration${NC}"
    echo -e "${YELLOW}Please check your Clerk application settings manually${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Configuration retrieved${NC}"

# Generate environment files
echo ""
echo -e "${BLUE}Generating environment files...${NC}"

# Backend environment (.env.local)
cat > .env.local << EOF
# RaptorFlow Backend Configuration - Generated by setup-clerk.sh
# DO NOT commit this file to version control

# Clerk Authentication
RAPTORFLOW_CLERK_ISSUER=$issuer_url
RAPTORFLOW_CLERK_JWKS_URL=${issuer_url}/.well-known/jwks.json
RAPTORFLOW_CLERK_WEBHOOK_SECRET=$webhook_secret

APP_ENV=dev
EOF

# Frontend environment
cat > apps/web/.env.local << EOF
# RaptorFlow Frontend Configuration - Generated by setup-clerk.sh
# DO NOT commit this file to version control

# Clerk Authentication
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$publishable_key
NEXT_PUBLIC_API_BASE_URL=http://localhost:8080
EOF

echo -e "${GREEN}✅ Environment files generated${NC}"
echo ""
echo -e "${BLUE}📝 Next Steps:${NC}"
echo -e "1. Review the generated .env.local files"
echo -e "2. Add your Clerk secret key to .env.local:"
echo -e "   CLERK_SECRET_KEY=sk_..."
echo -e "   (Get this from Clerk Dashboard → API Keys)"
echo -e "3. Start the infrastructure:"
echo -e "   docker compose up -d postgres pgbouncer qdrant"
echo -e "4. Run the health check:"
echo -e "   ./scripts/healthcheck.sh"
echo -e "5. Start the API:"
echo -e "   cargo run -p raptorflow-api"
echo ""

echo -e "${GREEN}🎉 Clerk setup complete!${NC}"
