'use client';

import React, { useState, useEffect } from 'react';
import { StrategicPivotCard } from '../campaigns/StrategicPivotCard';
import { Sparkles } from 'lucide-react';
import { toast } from 'sonner';
import { applyCampaignPivot } from '@/lib/campaigns';

interface StrategicPivot {
  id: string;
  campaignId: string;
  title: string;
  description: string;
  rationale: string;
  severity: 'low' | 'medium' | 'high';
}

/**
 * SOTA Strategic Pivot List
 * Fetches and displays multiple agentic recommendations in the dashboard.
 */
import { getLearningFeed } from '@/lib/blackbox';

// ...

export function StrategicPivotList() {
  const [pivots, setPivots] = useState<StrategicPivot[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    const fetchPivots = async () => {
      setIsLoading(true);
      try {
        const feed = await getLearningFeed();
        // Map backend learning to StrategicPivot frontend type
        const mappedPivots: StrategicPivot[] =
          feed && feed.length > 0
            ? feed.map((item: any) => ({
                id: item.id,
                campaignId: item.campaign_id || 'c1',
                title:
                  item.learning_type === 'strategic'
                    ? 'Strategic Shift'
                    : 'Tactical Optimization',
                description: item.content,
                rationale:
                  'Generated by Agentic Spine based on recent telemetry.',
                severity:
                  item.learning_type === 'strategic' ? 'high' : 'medium',
              }))
            : [];

        if (mappedPivots.length > 0) {
          setPivots(mappedPivots);
        } else {
          // FALLBACK MOCK DATA FOR "UNAUTH"/DEV MODE
          setPivots([
            {
              id: 'mock-1',
              campaignId: 'c1',
              title: 'Strategic Shift',
              description:
                'Competitor "AcmeCorp" just dropped pricing by 20%. Recommend updating "Value" campaign to emphasize TCO.',
              rationale: 'Detected via Radar module.',
              severity: 'high',
            },
            {
              id: 'mock-2',
              campaignId: 'c1',
              title: 'Tactical Optimization',
              description:
                'LinkedIn organic reach is down 15%. Shift 2 posts/week to Twitter/X.',
              rationale: 'Detected via Muse analytics.',
              severity: 'medium',
            },
          ]);
        }
      } catch (err) {
        console.error('Failed to fetch pivots', err);
        // FALLBACK MOCK DATA ON ERROR
        setPivots([
          {
            id: 'mock-1',
            campaignId: 'c1',
            title: 'Strategic Shift',
            description:
              'Competitor "AcmeCorp" just dropped pricing by 20%. Recommend updating "Value" campaign to emphasize TCO.',
            rationale: 'Detected via Radar module.',
            severity: 'high',
          },
          {
            id: 'mock-2',
            campaignId: 'c1',
            title: 'Tactical Optimization',
            description:
              'LinkedIn organic reach is down 15%. Shift 2 posts/week to Twitter/X.',
            rationale: 'Detected via Muse analytics.',
            severity: 'medium',
          },
        ]);
      } finally {
        setIsLoading(false);
      }
    };

    fetchPivots();
  }, []);

  const handleApply = async (id: string) => {
    const pivot = pivots.find((p) => p.id === id);
    if (!pivot) return;

    toast.promise(applyCampaignPivot(pivot.campaignId, pivot as any), {
      loading: 'Applying strategy shift...',
      success: 'Strategy shift applied successfully',
      error: 'Failed to apply shift',
    });

    // Task 22 implementation completed
    setPivots((prev) => prev.filter((p) => p.id !== id));
  };
  const handleIgnore = (id: string) => {
    toast('Recommendation archived');
    setPivots((prev) => prev.filter((p) => p.id !== id));
  };

  if (pivots.length === 0 && !isLoading) return null;

  return (
    <section className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-1000">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-full bg-accent/10 text-accent">
            <Sparkles size={20} />
          </div>
          <div>
            <h2 className="text-2xl font-display font-medium tracking-tight">
              Strategic Intelligence
            </h2>
            <p className="text-sm text-muted-foreground">
              Agent recommendations based on real-time market signals.
            </p>
          </div>
        </div>
        {pivots.length > 1 && (
          <span className="text-[10px] font-bold uppercase tracking-widest px-2 py-1 bg-zinc-100 dark:bg-zinc-800 rounded-full">
            {pivots.length} New Signals
          </span>
        )}
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
        {isLoading ? (
          <div className="col-span-full h-48 rounded-2xl border border-dashed border-zinc-200 dark:border-zinc-800 animate-pulse bg-zinc-50/50 dark:bg-zinc-900/20" />
        ) : (
          pivots.map((pivot) => (
            <StrategicPivotCard
              key={pivot.id}
              pivot={pivot}
              onApply={handleApply}
              onIgnore={handleIgnore}
            />
          ))
        )}
      </div>
    </section>
  );
}
