export const FOUNDATION_STEPS = [
  { id: "url", title: "Where Does Your Business Live?", description: "Paste your website URL. We'll scan it to pre-fill the rest of this foundation.", placeholder: "https://yourwebsite.com", section: "company_url" },
  { id: "identity-confirmation", title: "Tell Me About Your Business", description: "Confirm your core identity so our agents understand who they represent.", section: "company_info" },
  { id: "business-stage-and-team", title: "Business Stage & Capacity", description: "Our agents calibrate their campaign ambition to your actual bandwidth.", section: "company_stage" },
  { id: "what-you-actually-sell", title: "What Do You Offer?", description: "List your main offerings. Focus on the customer outcome, not just features.", section: "product_catalog" },
  { id: "the-problem-you-solve", title: "What Problem Do You Solve?", description: "The most important question: what was your customer's situation before they found you?", section: "problem_statement" },
  { id: "primary-icp", title: "Your Primary Ideal Customer Profile", description: "Define the primary target customer in depth.", section: "target_audience" },
  { id: "secondary-icps", title: "Secondary Customer Profiles (Optional)", description: "Do you serve other distinct customer groups?", section: "secondary_icps" },
  { id: "competitive-landscape", title: "Who Are Your Competitors?", description: "List the competitors your customers choose between when deciding to buy.", section: "competitors" },
  { id: "competitive-differentiation", title: "Your Clear Differentiation", description: "Why do buyers choose you over the alternatives listed previously?", section: "differentiation" },
  { id: "positioning-statement", title: "Your Strategic Position", description: "How you occupy a distinct place in your market.", section: "positioning" },
  { id: "brand-personality", title: "Brand Voice & Personality", description: "The consistent voice, tone, and character of your brand.", section: "brand_personality" },
  { id: "voice-in-practice", title: "Give Us An Example", description: "Paste concrete examples of your brand voice in real content.", section: "voice_practice" },
  { id: "content-territories", title: "Content Territories", description: "The thematic areas your content explores and owns.", section: "content_territories" },
  { id: "marketing-channels", title: "Proven Channels", description: "The channels that actually work to reach your ICP.", section: "channels" },
  { id: "goals-and-kpis", title: "Hard Goals & KPIs", description: "The business outcomes you are optimizing marketing toward.", section: "goals" },
  { id: "keywords-and-seo", title: "Discoverability", description: "Search terms and organic visibility targets.", section: "seo_keywords" },
  { id: "existing-assets", title: "Your Core Assets", description: "Collateral, content, and materials you already have.", section: "asset_inventory" },
  { id: "current-frustrations", title: "The Handbrake", description: "What is broken, slow, or failing in your current marketing.", section: "frustrations" },
  { id: "existing-tools", title: "The Tech Stack", description: "Your current marketing stack and how it is used.", section: "tools" },
  { id: "reference-brands", title: "Reference Brands", description: "Brands you admire or aspire to — for tone, style, or strategy.", section: "reference_brands" },
  { id: "campaign-strategist", title: "Your Campaign Strategist", description: "Configure your primary AI architect's briefing style and priorities.", section: "strategist" },
] as const;
